import { normalizeSeoRequest, seoRequestFingerprint, unavailableProviderResult } from "../provider.mjs";

const SERP_TTL_MS=Number(process.env.SEO_SERP_TTL_HOURS||48)*60*60*1000;
export function normalizeSerpApiResponse(raw,request,fetchedAt=new Date().toISOString()){
 const organic=(raw.organic_results||[]).map((item,index)=>({position:Number(item.position||index+1),resultType:"organic",title:String(item.title||""),url:String(item.link||""),domain:item.link?new URL(item.link).hostname.replace(/^www\./,""):"",snippet:String(item.snippet||""),displayedDate:item.date||null}));
 const questions=(raw.related_questions||[]).map((item,index)=>({position:index+1,question:String(item.question||""),answer:String(item.snippet||item.answer||""),sourceTitle:String(item.title||""),sourceUrl:String(item.link||"")}));
 const relatedSearches=(raw.related_searches||[]).map((item,index)=>({position:index+1,query:String(item.query||item.block_position||"")})).filter(item=>item.query);
 const featureMap={answer_box:"answer_box",knowledge_graph:"knowledge_graph",featured_snippet:"featured_snippet",local_results:"local_pack",inline_images:"images",top_stories:"top_stories",inline_videos:"videos",shopping_results:"shopping"};
 const serpFeatures=Object.entries(featureMap).filter(([key])=>raw[key]!=null).map(([,value])=>value);
 return{organic,questions,relatedSearches,serpFeatures,resultCount:organic.length,searchMetadata:{googleUrl:raw.search_metadata?.google_url||null,rawStatus:raw.search_metadata?.status||null},fetchedAt,request};
}
export function createSerpApiProvider({apiKey=process.env.SERP_API_KEY,httpClient=fetch,now=()=>new Date()}={}){
 return{id:"serpapi",capabilities:["serp","related_keywords"],supports(capability){return this.capabilities.includes(capability);},async fetch(capability,input){if(!this.supports(capability))return unavailableProviderResult(this.id,capability,"SerpApi does not supply this capability in Auctor.",input);const request=normalizeSeoRequest(input),fetchedAt=now().toISOString(),expiresAt=new Date(now().getTime()+SERP_TTL_MS).toISOString();if(!apiKey)return{...unavailableProviderResult(this.id,capability,"SERP_API_KEY is not configured.",request),error:{code:"MISSING_CREDENTIAL",message:"SERP_API_KEY is not configured."}};try{const query=new URLSearchParams({engine:"google",q:request.keyword,google_domain:"google.co.in",gl:request.country.toLowerCase(),hl:request.language,num:"10",device:request.device,api_key:apiKey}),response=await httpClient(`https://serpapi.com/search.json?${query}`);if(!response.ok)throw Object.assign(new Error(`SerpApi returned HTTP ${response.status}.`),{code:`HTTP_${response.status}`});const raw=await response.json();if(raw.error)throw Object.assign(new Error(String(raw.error)),{code:"PROVIDER_ERROR"});return{provider:this.id,capability,status:"SUCCESS",sourceType:"PROVIDER",fetchedAt,expiresAt,requestFingerprint:seoRequestFingerprint(this.id,capability,request),requestMetadata:request,costMetadata:{requestCount:1,amount:null,currency:null},error:null,data:normalizeSerpApiResponse(raw,request,fetchedAt)};}catch(error){return{provider:this.id,capability,status:"FAILED",sourceType:"PROVIDER",fetchedAt:null,expiresAt:null,requestFingerprint:seoRequestFingerprint(this.id,capability,request),requestMetadata:request,costMetadata:{requestCount:1,amount:null,currency:null},error:{code:error.code||"REQUEST_FAILED",message:error instanceof Error?error.message:String(error)},data:null};}}};
}
