"use client";
/* eslint-disable @typescript-eslint/no-explicit-any -- Existing image frontmatter metadata. */
import { useEffect, useRef, useState } from "react";
export type ImageInput = {direction?:string;role?:string;file?:File;concept?:string;alt?:string};
type Props = {data:Record<string,any>;busy:boolean;dirty:boolean;placement:string;headings:{label:string;value:string}[];onPlacement:(value:string)=>void;onImage:(action:string,id?:string,input?:ImageInput)=>Promise<void>|void};
const button="text-xs text-orange-300 underline underline-offset-2 disabled:opacity-40";
const field="mt-2 w-full min-w-0 rounded-lg border border-white/10 bg-[#101522] p-2 text-sm";
export default function ImageTools({data,busy,dirty,placement,headings,onPlacement,onImage}:Props) {
  const [adding,setAdding]=useState(false),[mode,setMode]=useState(""),[direction,setDirection]=useState(""),[replacement,setReplacement]=useState<any>(null),[replacementDirection,setReplacementDirection]=useState(""),[replacementRole,setReplacementRole]=useState(""),[role,setRole]=useState("human"),[concept,setConcept]=useState(""),[alt,setAlt]=useState(""),[file,setFile]=useState<File>(),[preview,setPreview]=useState<any>(null);
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(preview){if(dialog.current?.showModal)dialog.current.showModal();else dialog.current?.setAttribute("open","");}},[preview]);
  const disabled=busy||dirty;
  const images:any[]=data.inlineImages||[];
  const startReplacement=(image:any)=>{setReplacement(image);setReplacementDirection("");setReplacementRole("");};
  const thumb=(image:any)=><button type="button" aria-label={`Preview ${image.alt||image.conceptDescription||"image"}`} onClick={()=>setPreview(image)} className="shrink-0"><img src={image.src} alt={image.alt||""} className="h-20 w-28 rounded-lg object-cover"/></button>;
  return <>
    <div className="rounded-xl bg-black/20 p-4 text-sm text-slate-400"><h3 className="font-semibold text-white">Images</h3><p className="mt-2">Human images: {data.editorialRequirements?.humanImages||0}/2 distinct concepts required</p><p className="mt-1 text-xs">Supporting visuals: {data.editorialRequirements?.supportingVisuals||0} (optional). Counts reflect accepted, saved images.</p>{dirty&&<p className="mt-2 text-orange-300">Save &amp; Revalidate your edits before changing images.</p>}<button disabled={disabled} onClick={()=>setAdding(!adding)} className={`mt-3 ${button}`}>+ Add Image</button></div>
    {adding&&<div className="space-y-3 rounded-xl bg-black/20 p-4"><div className="flex flex-wrap gap-4"><button className={button} onClick={()=>setMode("generate")}>Generate with Birbal</button><button className={button} onClick={()=>setMode("upload")}>Upload Image</button></div>{mode&&<><label className="block text-xs">Placement / section<select className={field} value={placement} onChange={e=>onPlacement(e.target.value)}>{headings.map(h=><option key={h.value} value={h.value}>{h.label}</option>)}</select></label>{mode==="generate"?<><label className="block text-xs">Image direction (optional)<textarea maxLength={4000} className={field} placeholder="Tell Birbal what you want the images to show..." value={direction} onChange={e=>setDirection(e.target.value)}/></label><div className="flex flex-wrap gap-4"><button disabled={disabled||!placement} className={button} onClick={()=>void onImage("add-inline",undefined,{direction})}>Generate image</button><button disabled={disabled||!placement} className={button} onClick={()=>void onImage("plan-inline",undefined,{direction})}>Plan images for this draft</button></div></>:<><label className="block text-xs">Image file (PNG, JPEG, WebP; max 10 MB)<input aria-label="Image file" type="file" accept="image/png,image/jpeg,image/webp" className={field} onChange={e=>setFile(e.target.files?.[0])}/></label><label className="block text-xs">Role<select className={field} value={role} onChange={e=>setRole(e.target.value)}><option value="human">Human</option><option value="supporting_visual">Supporting visual</option></select></label><label className="block text-xs">Visual concept<textarea maxLength={4000} className={field} placeholder="Describe the action and story this image shows" value={concept} onChange={e=>setConcept(e.target.value)}/></label><label className="block text-xs">Alt text (optional)<input maxLength={500} className={field} value={alt} onChange={e=>setAlt(e.target.value)}/></label><button className={button} disabled={disabled||!placement||!file||!concept.trim()} onClick={()=>void onImage("upload-inline",undefined,{file,role,concept,alt})}>Upload for review</button></>}</>}</div>}
    {replacement&&<div className="rounded-xl border border-orange-400/30 bg-black/20 p-4" role="region" aria-label="Replace image"><h3 className="font-semibold">Replace image</h3><label className="mt-2 block text-xs">What would you like instead?<textarea autoFocus maxLength={4000} className={field} value={replacementDirection} onChange={e=>setReplacementDirection(e.target.value)}/></label><label className="block text-xs">Replacement role<select className={field} value={replacementRole} onChange={e=>setReplacementRole(e.target.value)}><option value="">Keep current role unless my direction changes it</option><option value="human">Human</option><option value="supporting_visual">Supporting visual</option></select></label><div className="mt-3 flex gap-4"><button disabled={disabled||!replacementDirection.trim()} className={button} onClick={async()=>{await onImage(replacement.id==="featured"?"regenerate-featured":"regenerate-inline",replacement.id,{direction:replacementDirection,role:replacementRole||undefined});}}>Generate replacement</button><button disabled={busy} className={button} onClick={()=>setReplacement(null)}>Cancel</button></div></div>}
    {([["Needs Review",images.filter(i=>i.status==="proposed")],["Accepted",images.filter(i=>i.status==="generated"&&i.target!=="featured")],["Failed",images.filter(i=>["failed","placement-unresolved"].includes(i.status))]] as [string,any[]][]).map(([title,items])=><div key={title} className="rounded-xl bg-black/20 p-4 text-sm text-slate-400"><h3 className="font-semibold text-white">{title}</h3>{title==="Accepted"&&data.image&&<div data-image-id="featured" className="mt-3 flex flex-wrap gap-3">{thumb({src:data.image,alt:data.imageAlt})}<div><p>Featured {data.featuredImageRole==="supporting_visual"?"supporting visual":"human image"}</p><p className="line-clamp-2 text-xs">{data.featuredConceptDescription||"Featured editorial concept"}</p><p className="text-xs">AI ? featured ? accepted</p><div className="mt-2 flex gap-3"><button disabled={disabled} className={button} onClick={()=>startReplacement({id:"featured"})}>Replace</button><button disabled={disabled} className={button} onClick={()=>void onImage("remove-featured")}>Remove</button></div></div></div>}{!items.length&&!(title==="Accepted"&&data.image)&&<p className="mt-2 text-xs">No {title.toLowerCase()} images.</p>}{items.map(item=><div key={item.id} data-image-id={item.id} className="mt-3 flex flex-wrap gap-3 border-t border-white/10 pt-3">{item.src&&thumb(item)}<div className="min-w-0 flex-1"><p className="line-clamp-2 text-xs text-slate-200" title={item.conceptDescription||item.purpose}>{item.conceptDescription||item.purpose||"Editorial image"}</p><p className="mt-1 text-xs">{item.role==="human"?"Human":"Supporting visual"} · {item.placement} · {item.source==="uploaded"?"Uploaded":"AI"} · {item.status}</p>{item.replaces&&<p className="text-xs">Replacement awaiting Keep; the current image stays until accepted.</p>}{item.error&&<details className="text-xs text-red-300"><summary>Failure details</summary>{item.error}</details>}<div className="mt-2 flex flex-wrap gap-3">{item.status==="proposed"&&<button disabled={disabled} className={button} onClick={()=>void onImage("accept-inline",item.id)}>Keep and insert</button>}<button disabled={disabled} className={button} onClick={()=>void onImage("remove-inline",item.id)}>{item.status==="generated"?"Remove":"Discard"}</button><button disabled={disabled} className={button} onClick={()=>startReplacement(item)}>Replace</button></div></div></div>)}</div>)}
    {!data.image&&<button disabled={disabled} className={button} onClick={()=>startReplacement({id:"featured"})}>Generate featured image</button>}
    {preview&&<dialog ref={dialog} aria-label="Image preview" onCancel={()=>setPreview(null)} className="fixed inset-0 m-auto h-[min(90dvh,900px)] max-h-[95dvh] w-[min(95vw,1100px)] open:grid grid-rows-[auto_minmax(0,1fr)_auto] gap-3 rounded-xl bg-[#101522] p-4 text-white backdrop:bg-black/80"><button autoFocus className={button} onClick={()=>{dialog.current?.close?.();setPreview(null);}}>Close preview</button><img src={preview.src} alt={preview.alt||""} className="h-full min-h-0 w-full object-contain"/><p className="truncate text-sm">{preview.conceptDescription||preview.alt}</p></dialog>}
  </>;
}
