"use client";
/* eslint-disable @typescript-eslint/no-explicit-any -- CMS payloads contain validated JSON frontmatter from Supabase. */
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import SeoControlCenter,{ResearchDecisionCard,type ResearchDecision} from "./seo-control-center";

type Post={slug:string;title:string;category:string;status:string;primaryKeyword?:string;audience?:string;relevantExams?:string[];seoScore?:number;contentQualityScore?:number;updatedDate?:string;date?:string};
type KeywordMetrics={status:string;freshness:string;fetchedAt?:string;expiresAt?:string;provider:string;data:null|{searchVolume:number|null;cpc:number|null;currency?:string;competition:string|null;competitionIndex:number|null;keywordDifficulty:number|null;locationName?:string;languageCode?:string}};
type ResearchResult={keyword:string;provider:string;status:string;freshness:string;fetchedAt:string|null;expiresAt:string|null;data:null|{searchVolume:number|null;cpc:number|null;currency:string;competition:string|null;competitionIndex:number|null;keywordDifficulty:number|null;monthlySearches:{year:number;month:number;search_volume:number|null}[]};partialErrors:{metric:string;code:string}[];error:{code:string;message:string}|null;cost:number|null;requestCount:number;intelligence?:ResearchDecision};
type Topic={title:string;primaryQuery:string;opportunityScore:number;trendStatus:string;searchDemandEstimate:string;examRelevance:string[];contentGap:string;reason:string;signals:string[];scoreBreakdown:Record<string,number>;keywordMetrics?:KeywordMetrics;sources?:{serpApi?:string[]}};
type TopicIntelligence={generatedAt:string|null;region:string;evidenceAuthority?:string;researchSnapshotIds?:string[];sourceAvailability:{googleTrends:string;serpApi:string;dataForSeo?:string;exactSearchVolume:string;actualSearchPerformance?:string};refreshResult?:{status:"FULL_SUCCESS"|"PARTIAL_SUCCESS"|"FAILED";attemptedAt:string;sourceStatus:Record<string,string>;preservedPreviousData:boolean};scoreDefinition:{note:string}};
type InlineImage={id:string;type:string;placement:string;purpose:string;prompt:string;alt:string;src?:string;status:string;error?:string};
type LinkRecommendation={targetArticle:string;url:string;anchor:string;context:string;reason:string};
type Draft={slug:string;version:string;data:Record<string,any>;content:string;checks:{externalLinks:string[];seoIssues:string[]};internalLinkRecommendations?:LinkRecommendation[]};
const audiences=["General / Multi-exam","CAT","XAT","GMAT","GRE","CUET","CLAT","IPMAT","NMAT","SNAP","SSC","Banking","Other"];
const stageNames:Record<string,string>={researching:"Researching topic",brief:"Creating content brief",writing:"Writing article",reviewing:"Reviewing article",improving:"Improving article",featuredImage:"Generating featured image",imagePlanning:"Planning inline images",inlineImages:"Generating inline images",finalizing:"Finalizing draft"};
async function api<T=any>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,{...options,headers:{"content-type":"application/json",...(options?.headers||{})}});let body:unknown;try{body=await response.json()}catch{throw new Error("The server returned an unreadable response. Please retry.")}if(!body||typeof body!=="object")throw new Error("The server returned an invalid response. Please retry.");if(!response.ok)throw new Error("error" in body&&typeof body.error==="string"?body.error:"Request failed.");return body as T;}
function headingOptions(content:string){return [...content.matchAll(/^##\s+(.+)$/gm)].map(match=>({label:match[1],value:match[1].toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}));}

export default function BlogStudio(){
 const [data,setData]=useState<{posts:Post[];topics:Topic[];topicIntelligence:TopicIntelligence;categories:string[];qualityThreshold:number;researchedKeywords?:{keyword:string;fetchedAt:string;freshness:string}[];opportunityActions?:{keyword:string;score:number;confidence:number;action:string;article:string|null;why:string[];createdAt:string}[]}|null>(null);
 const [topic,setTopic]=useState(""),[audience,setAudience]=useState(audiences[0]),[job,setJob]=useState<any>(null);
 const [researchKeyword,setResearchKeyword]=useState(""),[researchResult,setResearchResult]=useState<ResearchResult|null>(null),[researchBusy,setResearchBusy]=useState(false),[researchError,setResearchError]=useState("");
 const [performance,setPerformance]=useState<{status:string;observations?:number;recommendations?:{type:string;action:string;reason:string;suggestion:string;article?:string;title?:string;queries?:string[];metrics?:{impressions:number;clicks:number;ctr:number|null;averagePosition:number|null};refreshPlan?:{missingContent:string[];suggestedSections:string[];titleMetaSuggestion:string|null;internalLinks:{targetArticle:string}[];approvalRequired:boolean}}[];reason?:string}|null>(null),[performanceBusy,setPerformanceBusy]=useState(false);
 const [selected,setSelected]=useState<Draft|null>(null),[editing,setEditing]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[placement,setPlacement]=useState(""),[imageBusy,setImageBusy]=useState("");
 const [studioError,setStudioError]=useState("");
 const requestLocks=useRef({research:false,generation:false,save:false});
 const refresh=useCallback(async()=>{try{const next=await api("/api/admin/blog");if(!Array.isArray(next.posts)||!Array.isArray(next.topics))throw new Error("Blog Studio returned incomplete data.");setData(next);setStudioError("")}catch(error){setStudioError((error as Error).message)}},[]);
 async function refreshIntelligence(){setBusy(true);setMessage("");try{const next=await api("/api/admin/blog?refresh=1");setData(next);const result=next.topicIntelligence?.refreshResult;setMessage(result?.status==="FULL_SUCCESS"?"SEO signals refreshed successfully.":result?.status==="PARTIAL_SUCCESS"?"SEO signals partially refreshed; review source status below.":"SEO signal refresh failed; previous data was preserved where available.")}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function research(seed?:string){if(requestLocks.current.research)return;requestLocks.current.research=true;setResearchBusy(true);setResearchError("");setResearchResult(null);try{const result=await api<ResearchResult>("/api/admin/blog/keyword-research",{method:"POST",body:JSON.stringify({keyword:seed||researchKeyword})});if(typeof result.keyword!=="string"||!Array.isArray(result.partialErrors)||!("data" in result)||result.data!==null&&(!result.data||typeof result.data!=="object"||!Array.isArray(result.data.monthlySearches))||result.intelligence&&(!Array.isArray(result.intelligence.opportunity?.why)||!Array.isArray(result.intelligence.cannibalization?.matches)||!Array.isArray(result.intelligence.internalLinks)))throw new Error("Keyword research returned an invalid result. Please retry.");setResearchResult(result);if(result.error)setResearchError(result.error.message);else if(result.partialErrors.length)setResearchError(`Some metrics are unavailable: ${result.partialErrors.map(item=>item.metric).join(", ")}.`)}catch(error){setResearchError((error as Error).message)}finally{requestLocks.current.research=false;setResearchBusy(false)}}
 function usePrimaryKeyword(){if(!selected||!researchResult?.data)return;setSelected({...selected,data:{...selected.data,primaryKeyword:researchResult.keyword}});setEditing(true);setMessage("Primary keyword selected. Save the draft to keep this change.")}
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{void api("/api/admin/blog/search-performance").then(setPerformance).catch(()=>setPerformance({status:"UNAVAILABLE",reason:"GSC evidence could not be loaded."}))},[]);
 async function syncPerformance(){setPerformanceBusy(true);try{await api("/api/admin/blog/search-performance",{method:"POST"});setPerformance(await api("/api/admin/blog/search-performance"));setMessage("Google Search Console observations synced.")}catch(error){setMessage((error as Error).message)}finally{setPerformanceBusy(false)}}
 useEffect(()=>{if(!job?.id||["complete","failed"].includes(job.status))return;const timer=setInterval(async()=>{try{const next=await api(`/api/admin/blog/status/${job.id}`);setJob(next);if(next.status==="complete"){clearInterval(timer);await refresh();if(next.result?.slug)await review(next.result.slug)}}catch(error){setMessage((error as Error).message)}},1500);return()=>clearInterval(timer)},[job?.id,job?.status,refresh]);
 async function generate(seed?:string,manualResearch=false){if(requestLocks.current.generation)return;requestLocks.current.generation=true;setBusy(true);setMessage("");try{const target=seed||topic;const result=await api<{jobId:string}>("/api/admin/blog/generate",{method:"POST",body:JSON.stringify({topic:target,audience,manualResearch})});if(!result.jobId)throw new Error("Article generation did not return a job. Please retry.");setTopic(target);setJob({id:result.jobId,status:"processing",stages:Object.fromEntries(Object.keys(stageNames).map(stage=>[stage,"pending"]))})}catch(error){setMessage((error as Error).message)}finally{requestLocks.current.generation=false;setBusy(false)}}
 function createFromResearch(seed:string){const relevance=researchResult?.intelligence?.opportunity.components?.find(item=>item.name==="Topical relevance")?.value;if(relevance==null&&!window.confirm("This keyword has low or uncertain relevance to Auctor's topic taxonomy. Continue and create a draft anyway?"))return;void generate(seed,true)}
 async function review(slug:string){try{const draft=await api(`/api/admin/blog/draft/${slug}`);setSelected(draft);setPlacement(headingOptions(draft.content)[0]?.value||"");setEditing(false)}catch(error){setMessage((error as Error).message)}}
 function researchFromCenter(keyword:string){setResearchKeyword(keyword);document.getElementById("keyword-research")?.scrollIntoView({behavior:"smooth",block:"center"});void research(keyword)}
 function focusArticle(slug:string){const post=data?.posts.find(item=>item.slug===slug);if(post?.status==="draft"){void review(slug);document.getElementById("draft-review")?.scrollIntoView({behavior:"smooth"});return}document.getElementById(`article-${slug}`)?.scrollIntoView({behavior:"smooth",block:"center"});setMessage(post?.status==="published"?"Review the published article, then use the existing unpublish and edit controls when you approve an update.":"Review this article in the content library.")}
 function reviewMerge(action:{keyword:string;article:string|null}){setResearchKeyword(action.keyword);if(action.article)focusArticle(action.article);setMessage("Compare the researched intent and existing article before choosing to merge or differentiate. No content was changed.")}
 async function save(){if(!selected||requestLocks.current.save)return;requestLocks.current.save=true;setBusy(true);try{setSelected(await api(`/api/admin/blog/draft/${selected.slug}`,{method:"PUT",body:JSON.stringify({data:selected.data,content:selected.content,expectedUpdatedAt:selected.version})}));setEditing(false);setMessage("Draft saved; inline images were preserved and deterministic checks updated.");await refresh()}catch(error){setMessage((error as Error).message)}finally{requestLocks.current.save=false;setBusy(false)}}
 async function fixAndRecheck(){if(!selected)return;setBusy(true);setMessage("Fixing the article and rechecking SEO, editorial quality, and required images…");try{const draft=await api("/api/admin/blog/fix",{method:"POST",body:JSON.stringify({slug:selected.slug})});setSelected(draft);setEditing(false);setMessage(draft.data.publishEligible?"Fix complete — this draft is ready to publish.":`Fix complete — ${(draft.data.publishEligibilityReasons||[]).length} issue(s) still need attention.`);await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function publish(){if(!selected||!confirm(`Publish ${selected.data.title}?`))return;setBusy(true);try{const result=await api("/api/admin/blog/publish",{method:"POST",body:JSON.stringify({slug:selected.slug})}),warnings:string[]=result.warnings||[];setMessage(warnings.length?`Published with warnings: ${warnings.join(" · ")}`:`Published successfully: ${result.publishedSlug}`);setSelected(null);await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function discard(){if(!selected||!confirm("Archive this draft without publishing it?"))return;setBusy(true);try{await api(`/api/admin/blog/draft/${selected.slug}`,{method:"DELETE"});setSelected(null);setMessage("Draft archived. It was not published.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function lifecycle(post:Post,action:string){if(!confirm(`${action} ${post.title}?`))return;setBusy(true);try{await api("/api/admin/blog/lifecycle",{method:"POST",body:JSON.stringify({slug:post.slug,action})});setMessage(`${post.title}: ${action} completed.`);await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function regenerate(){if(!selected||!confirm("Archive this version and generate a different article and image plan?"))return;setBusy(true);try{const result=await api("/api/admin/blog/regenerate",{method:"POST",body:JSON.stringify({slug:selected.slug,topic:selected.data.title,audience:selected.data.audience||audience})});setTopic(selected.data.title);setSelected(null);setJob({id:result.jobId,status:"processing",stages:Object.fromEntries(Object.keys(stageNames).map(stage=>[stage,"pending"]))});await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function image(action:string,id?:string){if(!selected)return;setBusy(true);setImageBusy(id||action);try{const draft=await api("/api/admin/blog/images",{method:"POST",body:JSON.stringify({slug:selected.slug,action,id,placement})});setSelected(draft);setMessage(action.includes("remove")?"Image removed.":"Image workflow completed.");}catch(error){setMessage((error as Error).message)}finally{setBusy(false);setImageBusy("")}}
 function retryBlockingImages(){if(!selected)return;const failed=(selected.data.inlineImages||[]).find((item:InlineImage)=>["failed","placement-unresolved"].includes(item.status)&&((item.src&&selected.content.includes(item.src))||selected.content.includes(`inline-image:${item.id}`)));if(!selected.data.image)return image("regenerate-featured");if(failed)return image("regenerate-inline",failed.id);return image("plan-inline");}
 function removeLink(link:string){if(!selected)return;const escaped=link.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");setSelected({...selected,content:selected.content.replace(new RegExp(`\\[([^\\]]+)\\]\\(${escaped}\\)`,"g"),"$1")});setEditing(true)}
 const stats=useMemo(()=>({published:data?.posts.filter(post=>post.status==="published").length||0,drafts:data?.posts.filter(post=>post.status==="draft").length||0,pending:data?.posts.filter(post=>post.status==="review").length||0,categories:data?.categories.length||0}),[data]);
 const inlineImages:InlineImage[]=selected?.data.inlineImages||[],headings=selected?headingOptions(selected.content):[];
 return <main className="min-h-screen bg-[#080b14] text-white"><div className="mx-auto max-w-7xl px-5 py-10">
  <header><p className="text-xs font-bold tracking-[.25em] text-orange-400">AUCTOR LABS</p><h1 className="mt-2 text-4xl font-bold">Blog Studio</h1><p className="mt-2 text-slate-400">Research, generate, review and publish Auctor Labs articles.</p></header>
  <section className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{Object.entries(stats).map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-3xl font-bold">{value}</p><p className="mt-1 capitalize text-slate-400">{label}</p></div>)}</section>
  {message&&<div className="mt-6 rounded-xl border border-orange-500/30 bg-orange-500/10 px-4 py-3 text-sm text-orange-100">{message}</div>}
  {imageBusy&&<div className="mt-3 rounded-xl border border-violet-500/30 bg-violet-500/10 px-4 py-3 text-sm text-violet-100">Generating image… This draft remains usable if the image call fails.</div>}
  <section className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_.8fr]">
   <div className="rounded-2xl border border-white/10 bg-white/[.03] p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Suggested Topics</h2><p className="mt-1 text-xs font-medium text-orange-300">SEO Intelligence · India</p></div><button disabled={busy} onClick={refreshIntelligence} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300">Refresh signals</button></div>
    {data?.topicIntelligence&&<div className="mt-3 rounded-lg bg-black/20 p-3 text-xs text-slate-500"><p>Last refreshed: {data.topicIntelligence.generatedAt?new Date(data.topicIntelligence.generatedAt).toLocaleString():"Data unavailable"}</p><p className="mt-1">Refresh: {data.topicIntelligence.refreshResult?.status||"CACHED"} · Evidence: {data.topicIntelligence.evidenceAuthority||"transitional"} · Snapshots: {data.topicIntelligence.researchSnapshotIds?.length||0}</p><span>Google Trends: {data.topicIntelligence.refreshResult?.sourceStatus.googleTrends||data.topicIntelligence.sourceAvailability.googleTrends}</span><span className="mx-2">·</span><span>SerpApi: {data.topicIntelligence.refreshResult?.sourceStatus.serpApi||data.topicIntelligence.sourceAvailability.serpApi}</span><span className="mx-2">·</span><span>DataForSEO: {data.topicIntelligence.sourceAvailability.dataForSeo||"UNAVAILABLE"}</span><span className="mx-2">·</span><span>CMS corpus: {data.topicIntelligence.refreshResult?.sourceStatus.cmsCorpus||"FALLBACK"}</span><p className="mt-1">{data.topicIntelligence.sourceAvailability.exactSearchVolume}</p><p className="mt-1 font-medium text-amber-300">ACTUAL AUCTOR SEARCH PERFORMANCE: {data.topicIntelligence.sourceAvailability.actualSearchPerformance||"UNAVAILABLE — GSC NOT CONNECTED"}</p></div>}
    <div className="mt-4 space-y-3">{data?.topics.map(item=><button key={item.primaryQuery} onClick={()=>setTopic(item.title)} className="w-full rounded-xl border border-white/10 p-4 text-left transition hover:border-orange-400/60 hover:bg-white/[.03]">
      <div className="flex justify-between gap-4"><b>{item.title}</b><span className="shrink-0 text-orange-300">Topic signal priority {item.opportunityScore}</span></div>
      <p className="mt-2 text-xs text-slate-400">Primary query: <span className="text-slate-300">{item.primaryQuery}</span></p>
      <div className="mt-3 flex flex-wrap gap-2">{item.signals.map(signal=><span key={signal} className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1 text-xs text-slate-300">{signal.includes("Rising")?"🔥 ":signal.includes("demand")||signal.includes("related")?"📈 ":signal.includes("gap")?"🟢 ":"🎯 "}{signal}</span>)}</div>
      <p className="mt-3 text-sm text-slate-400">{item.reason}</p>
      <p className="mt-2 text-xs text-slate-600">Trend: {item.trendStatus} · Demand estimate: {item.searchDemandEstimate} · Exams: {item.examRelevance.join(", ")} · Content gap: {item.contentGap}</p>
      <div className="mt-3 grid gap-1 rounded-lg bg-black/20 p-3 text-xs text-slate-400 sm:grid-cols-2"><p>Search volume: <b className="text-slate-200">{item.keywordMetrics?.data?.searchVolume??"UNAVAILABLE"}</b></p><p>CPC: <b className="text-slate-200">{item.keywordMetrics?.data?.cpc!=null?`${item.keywordMetrics.data.currency||"USD"} ${item.keywordMetrics.data.cpc}`:"UNAVAILABLE"}</b></p><p>Advertising competition: <b className="text-slate-200">{item.keywordMetrics?.data?.competitionIndex??item.keywordMetrics?.data?.competition??"UNAVAILABLE"}</b></p><p>Keyword difficulty: <b className="text-slate-200">{item.keywordMetrics?.data?.keywordDifficulty??"UNAVAILABLE"}</b></p><p className="sm:col-span-2">Provenance: {item.keywordMetrics?.provider||"DataForSEO"} · India · English · {item.keywordMetrics?.freshness||"UNAVAILABLE"}{item.keywordMetrics?.fetchedAt?` · ${new Date(item.keywordMetrics.fetchedAt).toLocaleString()}`:""}</p><p className="sm:col-span-2">SERP evidence: {item.sources?.serpApi?.length?`Observed through ${item.sources.serpApi.length} SerpApi seed query snapshot(s)`:"UNAVAILABLE for this exact query"}</p></div>
    </button>)}</div>
    {data?.topicIntelligence&&<p className="mt-4 text-xs text-slate-600">{data.topicIntelligence.scoreDefinition.note}</p>}
   </div>
   <div className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><h2 className="text-xl font-semibold">Write your own topic</h2><textarea value={topic} onChange={event=>setTopic(event.target.value)} className="mt-4 h-28 w-full rounded-xl border border-white/10 bg-black/30 p-3" placeholder="Enter a relevant editorial topic"/><label className="mt-4 block text-sm text-slate-300">Audience / Exam Focus<select value={audience} onChange={event=>setAudience(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#101522] p-3">{audiences.map(value=><option key={value}>{value}</option>)}</select></label><button disabled={busy||topic.trim().length<5} onClick={()=>void generate()} className="mt-5 w-full rounded-xl bg-orange-500 px-4 py-3 font-bold text-black disabled:opacity-40">Generate Article</button></div>
  </section>
  <section id="keyword-research" className="mt-6 rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-sm font-semibold">Keyword research</h2><p className="mt-1 text-xs text-slate-500">Research one target keyword when you need provider evidence. Fresh results are reused for 30 days.</p><div className="mt-3 flex flex-wrap gap-2"><input aria-label="Target keyword" value={researchKeyword} onChange={event=>setResearchKeyword(event.target.value)} className="min-w-[240px] flex-1 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm" placeholder="e.g. CAT VARC preparation"/><button disabled={researchBusy||researchKeyword.trim().length<3} onClick={()=>void research()} className="rounded-lg border border-orange-400/40 px-4 py-2 text-sm text-orange-300 disabled:opacity-40">{researchBusy?"Researching…":"Research Keyword"}</button></div>
   {researchError&&<p role="alert" className="mt-3 text-sm text-amber-300">{researchError}</p>}
   {researchResult&&<div className="mt-4 rounded-lg bg-black/20 p-4 text-sm"><div className="flex flex-wrap items-center gap-2"><b>{researchResult.keyword}</b><span className="rounded border border-white/10 px-2 py-0.5 text-xs text-slate-300">{researchResult.provider} · {researchResult.freshness}{researchResult.status==="PARTIAL"?" · PARTIAL":""}</span>{researchResult.fetchedAt&&<span className="text-xs text-slate-500">Fetched {new Date(researchResult.fetchedAt).toLocaleString()}</span>}</div>
    {researchResult.data?<><div className="mt-3 grid gap-2 text-slate-300 sm:grid-cols-2 lg:grid-cols-4"><p>Search volume: <b>{researchResult.data.searchVolume??"UNAVAILABLE"}</b></p><p>CPC: <b>{researchResult.data.cpc!=null?`${researchResult.data.currency} ${researchResult.data.cpc}`:"UNAVAILABLE"}</b></p><p>Advertising competition: <b>{researchResult.data.competitionIndex??researchResult.data.competition??"UNAVAILABLE"}</b></p><p>Keyword difficulty: <b>{researchResult.data.keywordDifficulty??"UNAVAILABLE"}</b></p></div><p className="mt-3 text-xs text-slate-500">Monthly searches (India):</p>{researchResult.data.monthlySearches?.length?<div className="mt-1 flex flex-wrap gap-2">{researchResult.data.monthlySearches.map(item=><span key={`${item.year}-${item.month}`} className="rounded bg-white/5 px-2 py-1 text-xs text-slate-400">{item.year}-{String(item.month).padStart(2,"0")}: {item.search_volume??"UNAVAILABLE"}</span>)}</div>:<p className="mt-1 text-xs text-slate-500">UNAVAILABLE</p>}{selected&&<button disabled={selected.data.primaryKeyword===researchResult.keyword} onClick={usePrimaryKeyword} className="mt-4 text-xs text-orange-300 underline disabled:text-slate-600">Use as primary keyword for open draft</button>}</>:<p className="mt-3 text-slate-500">No provider metrics available.</p>}{researchResult.freshness==="STALE"&&<p className="mt-2 text-xs text-amber-300">Historical data is stale; it is not fresh provider evidence.</p>}</div>}
  </section>
  {researchResult?.intelligence&&<ResearchDecisionCard keyword={researchResult.keyword} decision={researchResult.intelligence} busy={busy} onResearch={researchFromCenter} onCreate={createFromResearch} onArticle={focusArticle} onMerge={()=>reviewMerge({keyword:researchResult.keyword,article:researchResult.intelligence?.opportunity.article||null})}/>}
  <SeoControlCenter actions={data?.opportunityActions||[]} posts={data?.posts||[]} history={data?.researchedKeywords||[]} links={selected?.internalLinkRecommendations||[]} loading={!data&&!studioError} error={studioError} busy={busy} qualityThreshold={data?.qualityThreshold||80} performance={performance} performanceBusy={performanceBusy} onSync={()=>void syncPerformance()} onResearch={researchFromCenter} onCreate={keyword=>void generate(keyword)} onArticle={focusArticle} onMerge={reviewMerge}/>
  {job&&<section className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Generation progress</h2><span className={job.status==="failed"?"text-red-400":"text-orange-300"}>{job.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(stageNames).map(([key,label])=>{const state=job.stages?.[key]||"pending",detail=key==="inlineImages"&&job.progress?.total?` ${job.progress.current||0} of ${job.progress.total}`:"";return <div key={key} className="rounded-xl bg-black/20 px-4 py-3"><span className={state==="complete"?"text-emerald-400":state==="failed"?"text-red-400":state==="processing"?"text-orange-300":"text-slate-600"}>{state==="complete"?"✓":state==="failed"?"✕":state==="processing"?"●":"○"}</span><span className="ml-2 text-sm">{label}{detail}</span></div>})}</div>{job.error&&<p className="mt-4 text-red-400">{job.error}</p>}</section>}
  <section id="content-library" className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-6"><h2 className="text-xl font-semibold">Content library</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-white/10 text-slate-500"><tr>{["Title","Category","Audience","Status","On-page","AI quality","Updated","Actions"].map(label=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{data?.posts.map(post=><tr id={`article-${post.slug}`} key={post.slug} className="border-b border-white/5"><td className="max-w-sm px-3 py-4 font-medium">{post.title}</td><td className="px-3">{post.category}</td><td className="px-3 text-slate-400">{post.audience||post.relevantExams?.join(", ")||"—"}</td><td className="px-3 capitalize">{post.status}</td><td className="px-3">{post.seoScore??"—"}</td><td className="px-3">{post.contentQualityScore??"—"}</td><td className="px-3 text-slate-400">{post.updatedDate||post.date}</td><td className="px-3"><div className="flex gap-3">{post.status==="draft"&&<button onClick={()=>review(post.slug)} className="text-orange-300">Review / Edit</button>}{post.status==="published"&&<><a href={`/blog/${post.slug}`} target="_blank" className="text-slate-300">View</a><button onClick={()=>lifecycle(post,"unpublish")} className="text-amber-300">Unpublish</button></>}{post.status==="unpublished"&&<><button onClick={()=>lifecycle(post,"edit")} className="text-orange-300">Move to draft</button><button onClick={()=>lifecycle(post,"archive")} className="text-red-300">Archive</button></>}{post.status==="archived"&&<button onClick={()=>lifecycle(post,"restore")} className="text-emerald-300">Restore draft</button>}</div></td></tr>)}</tbody></table></div></section>
  {selected&&<section id="draft-review" className="mt-8 rounded-2xl border border-orange-500/20 bg-white/[.04] p-6">
   <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-orange-300">Draft review</p><h2 className="text-2xl font-bold">{selected.data.title}</h2></div><div className="flex flex-wrap gap-2"><button onClick={()=>setEditing(!editing)} className="rounded-lg border border-white/15 px-4 py-2">{editing?"Preview":"Edit Article"}</button>{(selected.data.publishWarnings||[]).length>0&&<button disabled={busy} onClick={fixAndRecheck} className="rounded-lg bg-orange-500 px-4 py-2 font-bold text-black disabled:opacity-50">Fix Issues</button>}<button onClick={regenerate} className="rounded-lg border border-white/15 px-4 py-2">Discard & Regenerate</button><button onClick={discard} className="rounded-lg border border-red-500/30 px-4 py-2 text-red-300">Discard</button><button disabled={busy||!selected.data.publishEligible} onClick={publish} className="rounded-lg bg-emerald-500 px-4 py-2 font-bold text-black disabled:cursor-not-allowed disabled:opacity-40">Publish</button></div></div>
   <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_300px]"><div>{editing?<div className="space-y-3"><input value={selected.data.title||""} onChange={event=>setSelected({...selected,data:{...selected.data,title:event.target.value}})} className="w-full rounded-xl border border-white/10 bg-black/30 p-3 text-xl font-semibold"/><input aria-label="Primary keyword" value={selected.data.primaryKeyword||""} onChange={event=>setSelected({...selected,data:{...selected.data,primaryKeyword:event.target.value}})} className="w-full rounded-xl border border-white/10 bg-black/30 p-3 text-sm" placeholder="Primary keyword"/><textarea value={selected.data.description||""} onChange={event=>setSelected({...selected,data:{...selected.data,description:event.target.value}})} className="h-24 w-full rounded-xl border border-white/10 bg-black/30 p-3"/><textarea value={selected.content} onChange={event=>setSelected({...selected,content:event.target.value})} className="h-[700px] w-full rounded-xl border border-white/10 bg-black/30 p-4 font-mono text-sm"/><button disabled={busy} onClick={save} className="rounded-xl bg-orange-500 px-5 py-3 font-bold text-black">Save Draft & Revalidate</button></div>:<iframe key={selected.data.updatedDate} title="Article preview" src={`/admin/blog/preview/${selected.slug}`} className="h-[900px] w-full rounded-xl border border-white/10 bg-[#0B0F1A]"/>}</div>
    <aside className="space-y-4">
     <Panel title="Publish readiness"><p>On-page score: {selected.data.seoScore??"—"} / 100</p><p>AI editorial quality: {selected.data.contentQualityScore??"—"} / 100</p>{selected.data.readiness==="ready"?<p className="mt-2 font-medium text-emerald-400">Ready ✓</p>:selected.data.readiness==="ready-with-warnings"?<p className="mt-2 font-medium text-amber-300">Ready with warnings</p>:<p className="mt-2 font-medium text-red-300">Blocked: {(selected.data.technicalBlockers||[]).join(" ")}</p>}{(selected.data.publishWarnings||[]).length>0&&<><p className="mt-2 font-medium text-amber-300">Warnings: {selected.data.publishWarnings.length}</p><ol className="mt-3 list-decimal space-y-3 pl-4 text-xs text-amber-100">{(selected.data.publishEligibilityIssues||[]).map((issue:any)=><li key={issue.id}><p>{issue.message}</p><button disabled={busy} onClick={issue.action==="retry-images"?retryBlockingImages:fixAndRecheck} className="mt-1 text-orange-300 underline underline-offset-2">{issue.actionLabel}</button></li>)}</ol></>}</Panel>
     {selected.data.auditReport&&<Panel title="Actionable SEO audit"><p>Overall evidence check: {selected.data.auditReport.overallScore}/100</p><p className="mt-1 text-xs text-slate-500">{selected.data.auditReport.basis}</p>{(selected.data.auditReport.fixes||[]).filter((fix:any)=>["CRITICAL","HIGH","MEDIUM"].includes(fix.severity)).map((fix:any,index:number)=><p key={index} className="mt-2 text-xs"><b className={fix.severity==="HIGH"?"text-red-300":"text-amber-300"}>{fix.severity}</b> · {fix.message}<span className="block text-slate-500">{fix.reason} · {fix.basis||"HEURISTIC"}</span></p>)}{selected.data.auditReport.unavailableSignals?.length>0&&<p className="mt-3 text-xs text-slate-500">Unavailable external signals: {selected.data.auditReport.unavailableSignals.join(", ")}. These are not scored as failures.</p>}</Panel>}
     <Panel title="Featured image">{selected.data.image&&<img src={selected.data.image} alt={selected.data.imageAlt||""} className="mt-3 rounded-lg"/>}<div className="mt-3 flex gap-3"><button disabled={busy} onClick={()=>image("regenerate-featured")} className="text-xs text-orange-300">Regenerate</button>{selected.data.image&&<button disabled={busy} onClick={()=>image("remove-featured")} className="text-xs text-red-300">Remove</button>}</div></Panel>
     <Panel title="Inline images"><p>{selected.data.inlineImageSummary?.planned||0} planned · {selected.data.inlineImageSummary?.generated||0} generated · {selected.data.inlineImageSummary?.failed||0} failed</p>{!inlineImages.length&&<p className="mt-2 text-xs text-slate-500">No inline images have been planned for this draft.</p>}{inlineImages.map(item=><div key={item.id} className="mt-4 border-t border-white/10 pt-3"><div className="flex justify-between gap-2"><b className="text-xs">{item.purpose}</b><span className={item.status==="generated"?"text-emerald-400":item.status==="failed"||item.status==="placement-unresolved"?"text-red-400":"text-amber-300"}>{item.status}</span></div><p className="mt-1 text-xs text-slate-500">{item.placement} · {item.type}</p>{item.src&&<img src={item.src} alt={item.alt} className="mt-2 rounded-md"/>}{item.error&&<p className="mt-2 text-xs text-red-300">Image generation failed: {item.error}</p>}<div className="mt-2 flex gap-3">{item.status!=="removed"&&<button disabled={busy} onClick={()=>image("regenerate-inline",item.id)} className="text-xs text-orange-300">{item.status==="failed"?"Retry":"Regenerate"}</button>}{item.status!=="removed"&&<button disabled={busy} onClick={()=>image("remove-inline",item.id)} className="text-xs text-red-300">Remove</button>}</div></div>)}<div className="mt-4 border-t border-white/10 pt-3"><label className="text-xs text-slate-400">Add image after section<select value={placement} onChange={event=>setPlacement(event.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-[#101522] p-2">{headings.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><button disabled={busy||!placement} onClick={()=>image("add-inline")} className="mt-2 text-xs text-orange-300">+ Add Image</button>{!inlineImages.length&&<button disabled={busy} onClick={()=>image("plan-inline")} className="ml-3 text-xs text-violet-300">Plan images for this draft</button>}</div></Panel>
     {selected.internalLinkRecommendations?.length? <Panel title="Suggested internal links">{selected.internalLinkRecommendations.map(link=><div key={link.url} className="mt-3 border-t border-white/10 pt-2 text-xs"><a href={link.url} target="_blank" className="font-medium text-orange-300">{link.targetArticle}</a><p className="mt-1">Anchor: “{link.anchor}” · Context: {link.context}</p><p className="mt-1 text-slate-500">{link.reason}</p></div>)}</Panel>:<Panel title="Suggested internal links"><p className="text-xs text-slate-500">No strong published-article match for this draft.</p></Panel>}
     <Panel title="Internal Links">{(selected.data.internalLinkStates||[]).map((item:any)=><div key={item.url} className="mt-3 text-xs"><span className={item.state==="VERIFIED"?"text-emerald-400":item.state==="BROKEN"?"text-red-400":"text-amber-300"}>{item.state}</span> — {item.anchor||item.url}<button onClick={()=>removeLink(item.url)} className="ml-2 text-red-300">Remove suggestion</button><div className="truncate text-slate-600">{item.url}</div></div>)}</Panel>
    </aside>
   </div>
  </section>}
 </div></main>
}

function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-xl bg-black/20 p-4 text-sm text-slate-400"><h3 className="font-semibold text-white">{title}</h3><div className="mt-2">{children}</div></div>}
