"use client";
/* eslint-disable @typescript-eslint/no-explicit-any -- CMS payloads contain validated JSON frontmatter from Supabase. */
import { useCallback, useEffect, useMemo, useState } from "react";

type Post={slug:string;title:string;category:string;status:string;audience?:string;relevantExams?:string[];seoScore?:number;contentQualityScore?:number;updatedDate?:string;date?:string};
type Topic={title:string;primaryQuery:string;opportunityScore:number;trendStatus:string;searchDemandEstimate:string;examRelevance:string[];contentGap:string;reason:string;signals:string[];scoreBreakdown:Record<string,number>};
type TopicIntelligence={generatedAt:string;region:string;sourceAvailability:{googleTrends:string;serpApi:string;exactSearchVolume:string};scoreDefinition:{note:string}};
type InlineImage={id:string;type:string;placement:string;purpose:string;prompt:string;alt:string;src?:string;status:string;error?:string};
type Draft={slug:string;version:string;data:Record<string,any>;content:string;checks:{externalLinks:string[];seoIssues:string[]}};
const audiences=["General / Multi-exam","CAT","XAT","GMAT","GRE","CUET","CLAT","IPMAT","NMAT","SNAP","SSC","Banking","Other"];
const stageNames:Record<string,string>={researching:"Researching topic",brief:"Creating content brief",writing:"Writing article",reviewing:"Reviewing article",improving:"Improving article",featuredImage:"Generating featured image",imagePlanning:"Planning inline images",inlineImages:"Generating inline images",finalizing:"Finalizing draft"};
async function api(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"content-type":"application/json",...(options?.headers||{})}}),body=await response.json();if(!response.ok)throw new Error(body.error||"Request failed.");return body;}
function headingOptions(content:string){return [...content.matchAll(/^##\s+(.+)$/gm)].map(match=>({label:match[1],value:match[1].toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}));}

export default function BlogStudio(){
 const [data,setData]=useState<{posts:Post[];topics:Topic[];topicIntelligence:TopicIntelligence;categories:string[];qualityThreshold:number}|null>(null);
 const [topic,setTopic]=useState(""),[audience,setAudience]=useState(audiences[0]),[job,setJob]=useState<any>(null);
 const [selected,setSelected]=useState<Draft|null>(null),[editing,setEditing]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[placement,setPlacement]=useState(""),[imageBusy,setImageBusy]=useState("");
 const refresh=useCallback(async()=>setData(await api("/api/admin/blog")),[]);
 async function refreshIntelligence(){setBusy(true);setMessage("");try{setData(await api("/api/admin/blog?refresh=1"));setMessage("SEO intelligence refreshed from the available search sources.")}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{if(!job?.id||["complete","failed"].includes(job.status))return;const timer=setInterval(async()=>{try{const next=await api(`/api/admin/blog/status/${job.id}`);setJob(next);if(next.status==="complete"){clearInterval(timer);await refresh();if(next.result?.slug)await review(next.result.slug)}}catch(error){setMessage((error as Error).message)}},1500);return()=>clearInterval(timer)},[job?.id,job?.status,refresh]);
 async function generate(){setBusy(true);setMessage("");try{const result=await api("/api/admin/blog/generate",{method:"POST",body:JSON.stringify({topic,audience})});setJob({id:result.jobId,status:"processing",stages:Object.fromEntries(Object.keys(stageNames).map(stage=>[stage,"pending"]))})}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function review(slug:string){try{const draft=await api(`/api/admin/blog/draft/${slug}`);setSelected(draft);setPlacement(headingOptions(draft.content)[0]?.value||"");setEditing(false)}catch(error){setMessage((error as Error).message)}}
 async function save(){if(!selected)return;setBusy(true);try{setSelected(await api(`/api/admin/blog/draft/${selected.slug}`,{method:"PUT",body:JSON.stringify({data:selected.data,content:selected.content,expectedUpdatedAt:selected.version})}));setEditing(false);setMessage("Draft saved; inline images were preserved and deterministic checks updated.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function fixAndRecheck(){if(!selected)return;setBusy(true);setMessage("Fixing the article and rechecking SEO, editorial quality, and required images…");try{const draft=await api("/api/admin/blog/fix",{method:"POST",body:JSON.stringify({slug:selected.slug})});setSelected(draft);setEditing(false);setMessage(draft.data.publishEligible?"Fix complete — this draft is ready to publish.":`Fix complete — ${(draft.data.publishEligibilityReasons||[]).length} issue(s) still need attention.`);await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function publish(){if(!selected||!confirm(`Publish ${selected.data.title}?`))return;setBusy(true);try{const result=await api("/api/admin/blog/publish",{method:"POST",body:JSON.stringify({slug:selected.slug})}),warnings:string[]=result.warnings||[];setMessage(warnings.length?`Published with warnings: ${warnings.join(" · ")}`:`Published successfully: ${result.publishedSlug}`);setSelected(null);await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function discard(){if(!selected||!confirm("Archive this draft without publishing it?"))return;setBusy(true);try{await api(`/api/admin/blog/draft/${selected.slug}`,{method:"DELETE"});setSelected(null);setMessage("Draft archived. It was not published.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function regenerate(){if(!selected||!confirm("Archive this version and generate a different article and image plan?"))return;setBusy(true);try{const result=await api("/api/admin/blog/regenerate",{method:"POST",body:JSON.stringify({slug:selected.slug,topic:selected.data.title,audience:selected.data.audience||audience})});setTopic(selected.data.title);setSelected(null);setJob({id:result.jobId,status:"processing",stages:Object.fromEntries(Object.keys(stageNames).map(stage=>[stage,"pending"]))});await refresh()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function image(action:string,id?:string){if(!selected)return;setBusy(true);setImageBusy(id||action);try{const draft=await api("/api/admin/blog/images",{method:"POST",body:JSON.stringify({slug:selected.slug,action,id,placement})});setSelected(draft);setMessage(action.includes("remove")?"Image removed.":"Image workflow completed.");}catch(error){setMessage((error as Error).message)}finally{setBusy(false);setImageBusy("")}}
 function retryBlockingImages(){if(!selected)return;const failed=(selected.data.inlineImages||[]).find((item:InlineImage)=>["failed","placement-unresolved"].includes(item.status)&&((item.src&&selected.content.includes(item.src))||selected.content.includes(`inline-image:${item.id}`)));if(!selected.data.image)return image("regenerate-featured");if(failed)return image("regenerate-inline",failed.id);return image("plan-inline");}
 function removeLink(link:string){if(!selected)return;const escaped=link.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");setSelected({...selected,content:selected.content.replace(new RegExp(`\\[([^\\]]+)\\]\\(${escaped}\\)`,"g"),"$1")});setEditing(true)}
 const stats=useMemo(()=>({published:data?.posts.filter(post=>post.status==="published").length||0,drafts:data?.posts.filter(post=>post.status==="draft").length||0,pending:data?.posts.filter(post=>post.status==="review").length||0,categories:data?.categories.length||0}),[data]);
 const inlineImages:InlineImage[]=selected?.data.inlineImages||[],headings=selected?headingOptions(selected.content):[];
 return <main className="min-h-screen bg-[#080b14] text-white"><div className="mx-auto max-w-7xl px-5 py-10">
  <header><p className="text-xs font-bold tracking-[.25em] text-orange-400">AUCTOR LABS</p><h1 className="mt-2 text-4xl font-bold">Blog Studio</h1><p className="mt-2 text-slate-400">Research, generate, review and publish Auctor Labs articles.</p></header>
  <section className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{Object.entries(stats).map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-3xl font-bold">{value}</p><p className="mt-1 capitalize text-slate-400">{label}</p></div>)}</section>
  {message&&<div className="mt-6 rounded-xl border border-orange-500/30 bg-orange-500/10 px-4 py-3 text-sm text-orange-100">{message}</div>}
  {imageBusy&&<div className="mt-3 rounded-xl border border-violet-500/30 bg-violet-500/10 px-4 py-3 text-sm text-violet-100">Generating image… This draft remains usable if the image call fails.</div>}
  <section className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_.8fr]">
   <div className="rounded-2xl border border-white/10 bg-white/[.03] p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Suggested Topics</h2><p className="mt-1 text-xs font-medium text-orange-300">SEO Intelligence · India</p></div><button disabled={busy} onClick={refreshIntelligence} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300">Refresh signals</button></div>
    {data?.topicIntelligence&&<div className="mt-3 rounded-lg bg-black/20 p-3 text-xs text-slate-500"><span>Google Trends: {data.topicIntelligence.sourceAvailability.googleTrends}</span><span className="mx-2">·</span><span>SerpApi: {data.topicIntelligence.sourceAvailability.serpApi}</span><p className="mt-1">{data.topicIntelligence.sourceAvailability.exactSearchVolume}</p></div>}
    <div className="mt-4 space-y-3">{data?.topics.map(item=><button key={item.primaryQuery} onClick={()=>setTopic(item.title)} className="w-full rounded-xl border border-white/10 p-4 text-left transition hover:border-orange-400/60 hover:bg-white/[.03]">
      <div className="flex justify-between gap-4"><b>{item.title}</b><span className="shrink-0 text-orange-300">SEO opportunity {item.opportunityScore}</span></div>
      <p className="mt-2 text-xs text-slate-400">Primary query: <span className="text-slate-300">{item.primaryQuery}</span></p>
      <div className="mt-3 flex flex-wrap gap-2">{item.signals.map(signal=><span key={signal} className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1 text-xs text-slate-300">{signal.includes("Rising")?"🔥 ":signal.includes("demand")||signal.includes("related")?"📈 ":signal.includes("gap")?"🟢 ":"🎯 "}{signal}</span>)}</div>
      <p className="mt-3 text-sm text-slate-400">{item.reason}</p>
      <p className="mt-2 text-xs text-slate-600">Trend: {item.trendStatus} · Demand estimate: {item.searchDemandEstimate} · Exams: {item.examRelevance.join(", ")} · Content gap: {item.contentGap}</p>
    </button>)}</div>
    {data?.topicIntelligence&&<p className="mt-4 text-xs text-slate-600">{data.topicIntelligence.scoreDefinition.note}</p>}
   </div>
   <div className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><h2 className="text-xl font-semibold">Write your own topic</h2><textarea value={topic} onChange={event=>setTopic(event.target.value)} className="mt-4 h-28 w-full rounded-xl border border-white/10 bg-black/30 p-3" placeholder="Enter a relevant editorial topic"/><label className="mt-4 block text-sm text-slate-300">Audience / Exam Focus<select value={audience} onChange={event=>setAudience(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#101522] p-3">{audiences.map(value=><option key={value}>{value}</option>)}</select></label><button disabled={busy||topic.trim().length<5} onClick={generate} className="mt-5 w-full rounded-xl bg-orange-500 px-4 py-3 font-bold text-black disabled:opacity-40">Generate Article</button></div>
  </section>
  {job&&<section className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Generation progress</h2><span className={job.status==="failed"?"text-red-400":"text-orange-300"}>{job.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(stageNames).map(([key,label])=>{const state=job.stages?.[key]||"pending",detail=key==="inlineImages"&&job.progress?.total?` ${job.progress.current||0} of ${job.progress.total}`:"";return <div key={key} className="rounded-xl bg-black/20 px-4 py-3"><span className={state==="complete"?"text-emerald-400":state==="failed"?"text-red-400":state==="processing"?"text-orange-300":"text-slate-600"}>{state==="complete"?"✓":state==="failed"?"✕":state==="processing"?"●":"○"}</span><span className="ml-2 text-sm">{label}{detail}</span></div>})}</div>{job.error&&<p className="mt-4 text-red-400">{job.error}</p>}</section>}
  <section className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-6"><h2 className="text-xl font-semibold">Content library</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-white/10 text-slate-500"><tr>{["Title","Category","Audience","Status","SEO","Quality","Updated","Actions"].map(label=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{data?.posts.map(post=><tr key={post.slug} className="border-b border-white/5"><td className="max-w-sm px-3 py-4 font-medium">{post.title}</td><td className="px-3">{post.category}</td><td className="px-3 text-slate-400">{post.audience||post.relevantExams?.join(", ")||"—"}</td><td className="px-3 capitalize">{post.status}</td><td className="px-3">{post.seoScore??"—"}</td><td className="px-3">{post.contentQualityScore??"—"}</td><td className="px-3 text-slate-400">{post.updatedDate||post.date}</td><td className="px-3">{post.status==="draft"?<button onClick={()=>review(post.slug)} className="text-orange-300">Review / Edit</button>:<a href={`/blog/${post.slug}`} target="_blank" className="text-slate-300">View</a>}</td></tr>)}</tbody></table></div></section>
  {selected&&<section className="mt-8 rounded-2xl border border-orange-500/20 bg-white/[.04] p-6">
   <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-orange-300">Draft review</p><h2 className="text-2xl font-bold">{selected.data.title}</h2></div><div className="flex flex-wrap gap-2"><button onClick={()=>setEditing(!editing)} className="rounded-lg border border-white/15 px-4 py-2">{editing?"Preview":"Edit Article"}</button>{(selected.data.publishWarnings||[]).length>0&&<button disabled={busy} onClick={fixAndRecheck} className="rounded-lg bg-orange-500 px-4 py-2 font-bold text-black disabled:opacity-50">Fix Issues</button>}<button onClick={regenerate} className="rounded-lg border border-white/15 px-4 py-2">Discard & Regenerate</button><button onClick={discard} className="rounded-lg border border-red-500/30 px-4 py-2 text-red-300">Discard</button><button disabled={busy||!selected.data.publishEligible} onClick={publish} className="rounded-lg bg-emerald-500 px-4 py-2 font-bold text-black disabled:cursor-not-allowed disabled:opacity-40">Publish</button></div></div>
   <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_300px]"><div>{editing?<div className="space-y-3"><input value={selected.data.title||""} onChange={event=>setSelected({...selected,data:{...selected.data,title:event.target.value}})} className="w-full rounded-xl border border-white/10 bg-black/30 p-3 text-xl font-semibold"/><textarea value={selected.data.description||""} onChange={event=>setSelected({...selected,data:{...selected.data,description:event.target.value}})} className="h-24 w-full rounded-xl border border-white/10 bg-black/30 p-3"/><textarea value={selected.content} onChange={event=>setSelected({...selected,content:event.target.value})} className="h-[700px] w-full rounded-xl border border-white/10 bg-black/30 p-4 font-mono text-sm"/><button disabled={busy} onClick={save} className="rounded-xl bg-orange-500 px-5 py-3 font-bold text-black">Save Draft & Revalidate</button></div>:<iframe key={selected.data.updatedDate} title="Article preview" src={`/admin/blog/preview/${selected.slug}`} className="h-[900px] w-full rounded-xl border border-white/10 bg-[#0B0F1A]"/>}</div>
    <aside className="space-y-4">
     <Panel title="Publish readiness"><p>SEO: {selected.data.seoScore??"—"} / 100</p><p>Editorial quality: {selected.data.contentQualityScore??"—"} / 100</p>{selected.data.publishEligible?<p className="mt-2 font-medium text-emerald-400">Ready to publish ✓</p>:<p className="mt-2 font-medium text-red-300">Technical blocker: {(selected.data.technicalBlockers||[]).join(" ")}</p>}{(selected.data.publishWarnings||[]).length>0&&<><p className="mt-2 font-medium text-amber-300">Warnings: {selected.data.publishWarnings.length}</p><ol className="mt-3 list-decimal space-y-3 pl-4 text-xs text-amber-100">{(selected.data.publishEligibilityIssues||[]).map((issue:any)=><li key={issue.id}><p>{issue.message}</p><button disabled={busy} onClick={issue.action==="retry-images"?retryBlockingImages:fixAndRecheck} className="mt-1 text-orange-300 underline underline-offset-2">{issue.actionLabel}</button></li>)}</ol></>}</Panel>
     <Panel title="Featured image">{selected.data.image&&<img src={selected.data.image} alt={selected.data.imageAlt||""} className="mt-3 rounded-lg"/>}<div className="mt-3 flex gap-3"><button disabled={busy} onClick={()=>image("regenerate-featured")} className="text-xs text-orange-300">Regenerate</button>{selected.data.image&&<button disabled={busy} onClick={()=>image("remove-featured")} className="text-xs text-red-300">Remove</button>}</div></Panel>
     <Panel title="Inline images"><p>{selected.data.inlineImageSummary?.planned||0} planned · {selected.data.inlineImageSummary?.generated||0} generated · {selected.data.inlineImageSummary?.failed||0} failed</p>{!inlineImages.length&&<p className="mt-2 text-xs text-slate-500">No inline images have been planned for this draft.</p>}{inlineImages.map(item=><div key={item.id} className="mt-4 border-t border-white/10 pt-3"><div className="flex justify-between gap-2"><b className="text-xs">{item.purpose}</b><span className={item.status==="generated"?"text-emerald-400":item.status==="failed"||item.status==="placement-unresolved"?"text-red-400":"text-amber-300"}>{item.status}</span></div><p className="mt-1 text-xs text-slate-500">{item.placement} · {item.type}</p>{item.src&&<img src={item.src} alt={item.alt} className="mt-2 rounded-md"/>}{item.error&&<p className="mt-2 text-xs text-red-300">Image generation failed: {item.error}</p>}<div className="mt-2 flex gap-3">{item.status!=="removed"&&<button disabled={busy} onClick={()=>image("regenerate-inline",item.id)} className="text-xs text-orange-300">{item.status==="failed"?"Retry":"Regenerate"}</button>}{item.status!=="removed"&&<button disabled={busy} onClick={()=>image("remove-inline",item.id)} className="text-xs text-red-300">Remove</button>}</div></div>)}<div className="mt-4 border-t border-white/10 pt-3"><label className="text-xs text-slate-400">Add image after section<select value={placement} onChange={event=>setPlacement(event.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-[#101522] p-2">{headings.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><button disabled={busy||!placement} onClick={()=>image("add-inline")} className="mt-2 text-xs text-orange-300">+ Add Image</button>{!inlineImages.length&&<button disabled={busy} onClick={()=>image("plan-inline")} className="ml-3 text-xs text-violet-300">Plan images for this draft</button>}</div></Panel>
     <Panel title="Internal Links">{(selected.data.internalLinkSuggestions||[]).map((item:any)=><div key={item.url} className="mt-3 text-xs"><span className="text-emerald-400">✓</span> {item.anchor}<button onClick={()=>removeLink(item.url)} className="ml-2 text-red-300">Remove</button><div className="truncate text-slate-600">{item.url}</div></div>)}</Panel>
    </aside>
   </div>
  </section>}
 </div></main>
}

function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-xl bg-black/20 p-4 text-sm text-slate-400"><h3 className="font-semibold text-white">{title}</h3><div className="mt-2">{children}</div></div>}
