import { NextResponse } from "next/server";
import OpenAI from "openai";
import { getBlogAdmin } from "@/lib/blog-admin-auth";
import { getCmsDraft,saveCmsDraft } from "@/lib/blog-cms-actions";
import { addCmsInlineImage,regenerateCmsFeaturedImage,regenerateCmsInlineImage } from "@/lib/blog-cms-images";
import { getCmsArticle,listCmsAssets,restoreLatestArticleRevision } from "@/lib/blog-cms-db";
import { getSeoCorpus } from "@/lib/seo/corpus";
import { recommendInternalLinks } from "@/lib/seo/intelligence.mjs";
import { applyBirbalOperations,birbalNeedsConfirmation,buildBirbalContext } from "@/lib/birbal-editor.mjs";
import { resolveOpenAiTextModel } from "@/lib/openai-model.mjs";

export const runtime="nodejs";export const maxDuration=300;
const operation={type:"object",additionalProperties:false,required:["type","target","replacement","summary"],properties:{type:{type:"string",enum:["replace_text","insert_after","set_title","set_description","image_add","image_replace_featured","image_replace_inline"]},target:{type:"string"},replacement:{type:"string"},summary:{type:"string"}}};
const schema={type:"object",additionalProperties:false,required:["reply","clarification","operations"],properties:{reply:{type:"string"},clarification:{type:["string","null"]},operations:{type:"array",items:operation,maxItems:8}}};

async function context(slug:string){const article=await getCmsArticle(slug,"draft");if(!article)throw new Error(`Draft not found: ${slug}`);const [assets,corpus]=await Promise.all([listCmsAssets(article.id),getSeoCorpus().catch(()=>[])]),recommend=recommendInternalLinks as unknown as (keyword:string,corpus:Record<string,unknown>[],excludeSlug:string)=>Record<string,unknown>[],build=buildBirbalContext as unknown as (input:{article:Record<string,unknown>;assets:Record<string,unknown>[];links:Record<string,unknown>[];performance:Record<string,unknown>[]})=>Record<string,unknown>,links=recommend(String(article.frontmatter.primaryKeyword||article.title),corpus as Record<string,unknown>[],slug),performance=Array.isArray(article.frontmatter.gscObservations)?article.frontmatter.gscObservations as Record<string,unknown>[]:[];return{article,context:build({article:article as unknown as Record<string,unknown>,assets:assets as Record<string,unknown>[],links,performance})};}
async function plan(message:string,editorContext:Record<string,unknown>,history:unknown[]=[]){if(!process.env.OPENAI_API_KEY)throw new Error("Birbal is unavailable because OPENAI_API_KEY is not configured.");const response=await new OpenAI({apiKey:process.env.OPENAI_API_KEY}).responses.create({model:resolveOpenAiTextModel(),store:false,instructions:"You are Birbal, Auctor Labs' careful AI editor. Use the supplied current-article context and recent conversation. Make the smallest targeted change that satisfies the explicit request. Never publish, delete sections, invent facts, expose internal metadata, or replace the full article. For replace_text, target must be an exact unique verbatim passage from article.content. For insert_after, target must be an exact unique heading line or paragraph. Use image actions only when explicitly requested. For every image_add operation, target must be an exact section ID from article.sections and replacement must contain a concrete, relevant visual generation brief; never leave replacement empty. If the request or target is ambiguous, return clarification and no operations. Preserve all unrelated content. Fix review findings individually. Return concise summaries.",input:JSON.stringify({request:message,conversationHistory:history.slice(-12),currentArticleContext:editorContext}),text:{format:{type:"json_schema",name:"birbal_edit",strict:true,schema}}});return JSON.parse(response.output_text);}
async function apply(admin:NonNullable<Awaited<ReturnType<typeof getBlogAdmin>>>,slug:string,operations:Record<string,string>[]){let draft=await getCmsDraft(slug);if(!draft)throw new Error(`Draft not found: ${slug}`);const textOps=operations.filter(operation=>!operation.type.startsWith("image_"));if(textOps.length){const edited=applyBirbalOperations({title:draft.data.title,description:draft.data.description,content:draft.content},textOps);draft=await saveCmsDraft(admin,slug,{data:{...draft.data,title:edited.title,description:edited.description},content:edited.content,expectedUpdatedAt:draft.version});}
 for(const operation of operations.filter(operation=>operation.type.startsWith("image_"))){if(operation.type==="image_add")draft=await addCmsInlineImage(admin,slug,operation.target,operation.replacement||operation.summary);else if(operation.type==="image_replace_featured")draft=await regenerateCmsFeaturedImage(admin,slug);else if(operation.type==="image_replace_inline")draft=await regenerateCmsInlineImage(admin,slug,operation.target);}
 return draft;
}

export async function GET(request:Request){const admin=await getBlogAdmin();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});try{const slug=new URL(request.url).searchParams.get("slug")||"",result=await context(slug);return NextResponse.json({context:result.context});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:String(error)},{status:400});}}
export async function POST(request:Request){const admin=await getBlogAdmin();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});try{const body=await request.json(),slug=String(body.slug||"");if(body.action==="undo"){await restoreLatestArticleRevision(admin,slug);return NextResponse.json({reply:"Birbal restored the previous revision.",draft:await getCmsDraft(slug),undone:true});}if(body.action==="apply"){const operations=Array.isArray(body.operations)?body.operations:[];return NextResponse.json({reply:"Birbal updated the article. The review and audit have been rerun.",draft:await apply(admin,slug,operations),applied:true});}const current=await context(slug),result=await plan(String(body.message||"").trim(),current.context,Array.isArray(body.history)?body.history:[]);if(result.clarification||!result.operations.length)return NextResponse.json({reply:result.clarification||result.reply,clarification:true});if(birbalNeedsConfirmation(result.operations))return NextResponse.json({reply:result.reply,proposal:result.operations,summary:result.operations.map((item:Record<string,string>)=>item.summary)});return NextResponse.json({reply:"Birbal updated the article. The review and audit have been rerun.",draft:await apply(admin,slug,result.operations),applied:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:String(error)},{status:400});}}
