import type {Metadata} from "next";
import LegalPage,{type LegalSection} from "../components/LegalPage";

export const metadata:Metadata={title:"Auctor Privacy Policy",description:"Privacy Policy for Auctor and its educational services.",alternates:{canonical:"https://auctorlabs.in/privacy-policy"},openGraph:{type:"website",url:"https://auctorlabs.in/privacy-policy",siteName:"Auctor Labs",title:"Auctor Privacy Policy",description:"Privacy Policy for Auctor and its educational services."}};

const sections:LegalSection[]=[
 {id:"information-we-collect",title:"Information We Collect",content:<><p>Depending on how you use Auctor, we may collect your name, email address, phone or mobile number, account credentials, and educational or profile information that you choose to provide. Information submitted through contact, trial, institute, download, or other forms is also included.</p><p>When you use our educational and testing services, we may process activity information such as assessments attempted, answers, scores, timing, progress, practice history, and other performance information needed to provide the service. We may also receive browser, device, IP address, diagnostic, security, and technical log information.</p></>},
 {id:"how-we-use-information",title:"How We Use Information",content:<><p>We use information to provide and improve Auctor, manage accounts, deliver requested educational and testing services, personalize relevant experiences, provide customer support, and send service or transactional communications.</p><p>We may also use information to secure our services, prevent misuse or fraud, understand product performance, perform analytics, troubleshoot problems, and comply with applicable legal obligations.</p></>},
 {id:"whatsapp-communications",title:"WhatsApp Communications",content:<><p>Auctor may use WhatsApp to communicate with people who provide their phone number, consent to receive relevant communications, or otherwise interact with Auctor through WhatsApp. Messages may include account and service communications, onboarding, reminders, trial-related messages, support responses, and other communications related to Auctor services.</p><p>For these purposes, we may process a WhatsApp phone number and message-related information, including message content, delivery information, and interaction history where available. You can ask us to stop non-essential WhatsApp communications. Auctor does not own or operate WhatsApp or Meta services; Meta and WhatsApp process information under their own terms and privacy policies.</p></>},
 {id:"cookies",title:"Cookies and Similar Technologies",content:<><p>Auctor may use cookies, local storage, pixels, and similar technologies needed for functionality, security, preferences, analytics, and understanding the effectiveness of communications or advertising. The marketing website currently uses Google and Meta measurement technologies. Your browser and device settings may allow you to block or delete some technologies, although doing so can affect functionality.</p></>},
 {id:"sharing",title:"How We Share Information",content:<><p>We may share information with vendors that process it on our behalf when necessary to operate Auctor. Current infrastructure may include Supabase for application data and authentication services, Vercel for website hosting and delivery, and Meta or WhatsApp Cloud API for WhatsApp messaging.</p><p>We may also disclose information when reasonably necessary to comply with law, protect users or our services, investigate abuse, or support a business reorganization. We do not describe these operational disclosures as a sale of personal information.</p></>},
 {id:"retention",title:"Data Retention",content:<><p>We retain information for as long as reasonably needed to provide the service, maintain account and assessment records, resolve disputes, enforce agreements, protect security, and meet applicable legal or operational requirements. Retention periods vary according to the type of information and why it is processed. Information may then be deleted, anonymized, or securely retained where continued retention is required.</p></>},
 {id:"security",title:"Data Security",content:<><p>We use reasonable administrative and technical safeguards intended to protect information from unauthorized access, alteration, loss, or misuse. No online system or transmission method can be guaranteed to be completely secure, so users should also protect their account credentials and contact us if they suspect unauthorized access.</p></>},
 {id:"rights",title:"User Rights and Choices",content:<><p>Depending on applicable law, you may ask to access, correct, or delete personal information, or object to or restrict certain processing. You may unsubscribe from optional email communications using available instructions and request that non-essential WhatsApp messages stop. We may need to verify your identity before completing a request.</p><p>Deletion instructions are available on our <a href="/data-deletion">Data Deletion Request</a> page.</p></>},
 {id:"children",title:"Children's Privacy",content:<><p>Auctor’s competitive-exam and educational services are not directed to children who cannot lawfully consent to the processing of their information without a parent or guardian. If you believe a child has provided personal information without appropriate authorization, contact us so we can review and take suitable action.</p></>},
 {id:"third-party-services",title:"Third-Party Services",content:<><p>Auctor may link to or operate with third-party websites and platforms. Their handling of information is governed by their own terms and privacy policies. This policy applies to Auctor’s processing and does not control independent third-party practices.</p></>},
 {id:"changes",title:"Changes to This Privacy Policy",content:<><p>We may update this policy as our services, practices, or legal obligations change. The current version will be posted on this page with its updated date. Material changes may also be communicated through an appropriate service channel.</p></>},
 {id:"contact",title:"Contact Us",content:<><p>For privacy questions or requests, email <a href="mailto:info@auctorlabs.in">info@auctorlabs.in</a>. Please do not include passwords or other sensitive credentials in your message.</p></>},
];
export default function PrivacyPolicy(){return <LegalPage title="Auctor Privacy Policy" introduction="This Privacy Policy explains how Auctor collects, uses, stores, shares, and protects information when people use our websites, educational products, testing services, and communications." sections={sections}/>;}
