import { normalizeSeoRequest, providerSupports, seoRequestFingerprint, unavailableProviderResult } from "./provider.mjs";
const inflight=new Map();
export async function refreshProviderEvidence({provider,capability,request,store,force=false,adminId="",paidDailyLimit=0,now=()=>new Date()}){
 const normalized=normalizeSeoRequest(request);if(!providerSupports(provider,capability))return unavailableProviderResult(provider.id,capability,`${provider.id} does not support ${capability}.`,normalized);
 const fingerprint=seoRequestFingerprint(provider.id,capability,normalized);
 if(!force&&store){const finder=capability==="trends"?store.findFreshTrend?.bind(store):capability==="keyword_metrics"||capability==="keyword_difficulty"?store.findFreshMetric?.bind(store):store.findFresh?.bind(store);const fresh=finder?await finder(fingerprint,now(),normalized):null;if(fresh)return{provider:provider.id,capability,status:"CACHED",freshness:"CACHED",sourceType:"PROVIDER",fetchedAt:fresh.fetched_at,expiresAt:fresh.expires_at,requestFingerprint:fingerprint,requestMetadata:normalized,costMetadata:{requestCount:0,amount:0,currency:null},error:null,data:fresh.data||fresh,snapshotIds:fresh.ids||[fresh.id]};}
 if(inflight.has(fingerprint))return inflight.get(fingerprint);
 const work=(async()=>{let run=null;try{run=store?await store.beginRun({provider:provider.id,capability,fingerprint,requestMetadata:normalized,adminId,paidDailyLimit}):null;if(run?.quotaExceeded)return{provider:provider.id,capability,status:"FAILED",freshness:"UNAVAILABLE",costMetadata:{requestCount:0,amount:0,currency:"USD"},error:{code:"QUOTA_EXCEEDED",message:"Daily keyword research limit reached. Try again tomorrow."},data:null};if(run?.deduplicated){for(let attempt=0;attempt<20;attempt++){await new Promise(resolve=>setTimeout(resolve,500));const fresh=await store.findFreshMetric(fingerprint,now(),normalized);if(fresh)return{provider:provider.id,capability,status:"CACHED",freshness:"CACHED",sourceType:"PROVIDER",fetchedAt:fresh.fetched_at,expiresAt:fresh.expires_at,costMetadata:{requestCount:0,amount:0,currency:null},error:null,data:fresh.data||fresh};}return{provider:provider.id,capability,status:"CACHED",freshness:"CACHED",sourceType:"PROVIDER",fetchedAt:null,expiresAt:null,requestFingerprint:fingerprint,requestMetadata:normalized,costMetadata:{requestCount:0,amount:0,currency:null},error:null,data:null,deduplicated:true,snapshotIds:[]};}const result=await provider.fetch(capability,normalized);let snapshotIds=[];if(result.status==="SUCCESS"&&store&&run){const persist=capability==="trends"?store.persistTrend?.bind(store):capability==="keyword_metrics"||capability==="keyword_difficulty"?store.persistKeywordMetrics?.bind(store):store.persistSerp?.bind(store);if(persist){const snapshot=await persist(run,result);snapshotIds=snapshot.ids||[snapshot.id];}}if(store&&run)await store.finishRun(run.id,result);if(result.status!=="SUCCESS"&&store?.findLatestMetric&&(capability==="keyword_metrics"||capability==="keyword_difficulty")){const historical=await store.findLatestMetric(fingerprint);return{...result,freshness:historical?"STALE":"UNAVAILABLE",historicalSnapshot:historical,snapshotIds:historical?.ids||[]};}return{...result,freshness:result.status==="SUCCESS"?"FRESH":result.status,snapshotIds};}catch(error){const failed={provider:provider.id,capability,status:"FAILED",freshness:"UNAVAILABLE",sourceType:"PROVIDER",fetchedAt:null,expiresAt:null,requestFingerprint:fingerprint,requestMetadata:normalized,costMetadata:{requestCount:0,amount:null,currency:null},error:{code:"EVIDENCE_STORE_FAILED",message:error instanceof Error?error.message:String(error)},data:null,snapshotIds:[]};if(store&&run?.id)await store.finishRun(run.id,failed);return failed;}finally{inflight.delete(fingerprint);}})();inflight.set(fingerprint,work);return work;
}
export function overallRefreshStatus(results,requiredProviders=[]){const required=results.filter(item=>requiredProviders.includes(item.provider));if(required.some(item=>item.status==="FAILED"||item.status==="UNAVAILABLE"))return results.some(item=>["SUCCESS","CACHED"].includes(item.status))?"PARTIAL_SUCCESS":"FAILED";return results.some(item=>item.status==="FAILED")?"PARTIAL_SUCCESS":"FULL_SUCCESS";}


