import type {Metadata} from "next";
import LegalPage,{type LegalSection} from "../components/LegalPage";

export const metadata:Metadata={title:"Auctor Terms of Service",description:"Terms of Service governing use of Auctor's services.",alternates:{canonical:"https://auctorlabs.in/terms"},openGraph:{type:"website",url:"https://auctorlabs.in/terms",siteName:"Auctor Labs",title:"Auctor Terms of Service",description:"Terms of Service governing use of Auctor's services."}};
const sections:LegalSection[]=[
 {id:"acceptance",title:"Acceptance of Terms",content:<p>By accessing or using Auctor’s websites, educational products, assessments, or related services, you agree to these Terms. If you do not agree, do not use the services. Additional terms presented for a particular feature or transaction also apply to that feature or transaction.</p>},
 {id:"eligibility",title:"Eligibility",content:<p>You must be legally capable of agreeing to these Terms. If applicable law requires permission from a parent, guardian, institution, or other authorized person, you may use the services only with that permission and supervision.</p>},
 {id:"accounts",title:"Account Registration",content:<p>You agree to provide accurate information, keep it reasonably current, protect your login credentials, and promptly notify Auctor of suspected unauthorized use. You are responsible for activity conducted through your account unless applicable law provides otherwise.</p>},
 {id:"responsibilities",title:"User Responsibilities",content:<p>You are responsible for using Auctor lawfully, following assessment instructions, checking whether educational information is suitable for your needs, and maintaining the devices and connectivity required to access the service.</p>},
 {id:"acceptable-use",title:"Acceptable Use",content:<><p>You must not:</p><ul><li>gain unauthorized access to accounts, systems, data, or restricted features;</li><li>interfere with service operation, security, or other users;</li><li>upload malicious code or use automated methods that place unreasonable load on the service;</li><li>copy, resell, publish, scrape, or distribute protected content except as expressly permitted;</li><li>use the service for unlawful, deceptive, abusive, or rights-infringing activity.</li></ul></>},
 {id:"services",title:"Auctor Services",content:<p>Auctor provides online educational, practice, assessment, testing, analysis, and related communication features. Available features may differ by product, plan, account, or stage of development. Descriptions on current product pages form part of the relevant service information but do not guarantee that every feature will always remain unchanged.</p>},
 {id:"educational-information",title:"Assessments, Practice Content and Educational Information",content:<p>Practice questions, assessments, explanations, scores, analytics, recommendations, and AI-assisted material are educational aids. They may contain limitations or errors and should be evaluated appropriately. Auctor does not guarantee admission, selection, examination results, score improvement, or any particular academic outcome.</p>},
 {id:"payments",title:"Payments, Subscriptions, Trials and Refunds",content:<p>If you purchase a paid service or start a trial, the pricing, duration, renewal information, eligibility, and any applicable payment or refund terms shown to you at that time will govern the transaction. We do not state a universal refund period here. Contact <a href="mailto:info@auctorlabs.in">info@auctorlabs.in</a> with billing questions. Nothing in these Terms limits rights that cannot legally be excluded.</p>},
 {id:"intellectual-property",title:"Intellectual Property",content:<p>Auctor’s software, branding, interface, original questions, explanations, text, graphics, and other service materials are protected by applicable intellectual-property laws. Except for limited personal use of the service as intended, these Terms do not transfer ownership or grant a right to reproduce or commercialize Auctor materials.</p>},
 {id:"user-content",title:"User Content",content:<p>You retain any rights you hold in content you submit. You permit Auctor to host, process, reproduce, and use that content only as reasonably necessary to operate, secure, support, and improve the services. You must have the right to submit the content and must not submit unlawful or harmful material.</p>},
 {id:"third-parties",title:"Third-Party Services",content:<p>Some features rely on or link to third-party services, including hosting, data, authentication, communications, and messaging providers. Third-party services may have their own terms and privacy practices, and Auctor is not responsible for independent third-party systems outside its control.</p>},
 {id:"availability",title:"Service Availability",content:<p>We work to keep Auctor available and reliable, but services may occasionally be interrupted, delayed, changed, or unavailable because of maintenance, security events, technical issues, third-party services, or circumstances outside reasonable control.</p>},
 {id:"disclaimers",title:"Disclaimers",content:<p>To the extent permitted by applicable law, Auctor is provided on an “as available” basis without warranties that every feature will be uninterrupted, error-free, or suitable for every individual purpose. Educational content does not replace professional advice where such advice is appropriate.</p>},
 {id:"liability",title:"Limitation of Liability",content:<p>To the extent permitted by applicable law, Auctor will not be liable for indirect, incidental, special, consequential, or punitive losses arising from use of or inability to use the service. Any limitation applies only to the extent legally permitted and does not exclude liability that cannot lawfully be limited.</p>},
 {id:"termination",title:"Suspension or Termination",content:<p>We may restrict or suspend access when reasonably necessary to address security risks, unlawful activity, material violations of these Terms, non-payment for paid services, or harm to Auctor or others. Users may stop using the service at any time and may request account-data deletion through the published process.</p>},
 {id:"service-changes",title:"Changes to the Service",content:<p>We may improve, add, remove, or modify features. Where practicable, we will provide appropriate notice when a change materially affects an ongoing paid service.</p>},
 {id:"term-changes",title:"Changes to These Terms",content:<p>We may update these Terms to reflect service, operational, or legal changes. Updated Terms will be posted here with a revised date. Continued use after an update takes effect constitutes acceptance where permitted by law.</p>},
 {id:"law",title:"Governing Law and Dispute Resolution",content:<p>These Terms are governed by the laws applicable to Auctor and the relevant transaction, without overriding mandatory consumer protections or jurisdictional rights. Before beginning formal proceedings, please contact <a href="mailto:info@auctorlabs.in">info@auctorlabs.in</a> so the parties can attempt to resolve the concern directly. Any unresolved dispute will be handled by the courts or process having lawful jurisdiction.</p>},
];
export default function Terms(){return <LegalPage title="Auctor Terms of Service" introduction="These Terms govern access to and use of Auctor's websites, educational products, assessments, testing tools, and related services." sections={sections}/>;}
