import "server-only";
/* eslint-disable @typescript-eslint/no-explicit-any -- validation and Supabase JSON payloads are runtime-shaped. */
import type { BlogAdmin } from "./blog-admin-auth";
import { archiveCmsArticle,getCmsArticle,listCmsArticles,listCmsAssets,updateCmsArticle } from "./blog-cms-db";
import { MIN_SCORE,repairArticleOnce,validateArticle } from "./blog-engine";
import { publicationPersistenceError,publicationTechnicalBlockers,referencedCmsAssets,sanitizeCmsPublicCopy } from "./blog-publish-policy";
import { classifyInternalLinks } from "./blog-links.mjs";
import { auditArticleIntelligence } from "./seo/intelligence.mjs";

const requiredFields=["title","description","date","image","imageAlt","category","author","primaryKeyword","secondaryKeywords","searchIntent","cluster","relevantExams","schemaType","seoScore","contentQualityScore"];
function normalizeMetaDescription(value:unknown){let text=String(value||"").replace(/\s+/g," ").trim();const supplement=" Learn practical methods, worked examples, and exam-focused guidance.";while(text.length<140)text+=supplement;if(text.length<=160)return text;let clipped=text.slice(0,159);const boundary=clipped.lastIndexOf(" ");if(boundary>=140)clipped=clipped.slice(0,boundary);return `${clipped.replace(/[\s,;:.!?-]+$/g,"")}.`;}
function deterministicSeoScore(checks:any){return Math.max(0,100-checks.seoIssues.length*15-(checks.externalLinks.length?40:0)-(checks.invalidInternalLinks.length?20:0));}
function eligibilityReasons(row:any,checks:any,assets:any[]){const data=row.frontmatter||{},reasons:string[]=[];const missing=requiredFields.filter(key=>data[key]===undefined||data[key]===null||data[key]==="");if(missing.length)reasons.push(`Missing required frontmatter: ${missing.join(", ")}`);if(Number(data.seoScore)<80)reasons.push(`SEO score ${data.seoScore??"—"} is below 80.`);if(Number(data.contentQualityScore)<MIN_SCORE)reasons.push(`Content quality score ${data.contentQualityScore??"—"} is below ${MIN_SCORE}.`);if(checks.seoIssues.length)reasons.push(`Unresolved SEO issues: ${checks.seoIssues.join(" | ")}`);if(checks.editorialIssues?.length)reasons.push(`Unresolved editorial issues: ${checks.editorialIssues.join(" | ")}`);if(checks.externalLinks.length)reasons.push(`External article-body links found: ${checks.externalLinks.join(", ")}`);if(checks.invalidInternalLinks.length)reasons.push(`Invalid internal links found: ${checks.invalidInternalLinks.join(", ")}`);const unresolved=referencedCmsAssets(row,assets).filter((asset:any)=>asset.status!=="generated"||!asset.public_url||!asset.storage_path||!asset.alt_text||(asset.asset_type==="featured"?data.image!==asset.public_url:!String(row.content||"").includes(asset.public_url)));if(unresolved.length)reasons.push(`Unresolved image assets: ${unresolved.map((asset:any)=>`${asset.image_key} (${asset.id}; ${asset.status})`).join(", ")}`);return reasons;}
function evaluate(row:any,assets:any[]=[],validInternalUrls:string[]=[]){const base=row.frontmatter||{},description=normalizeMetaDescription(row.description),checks=validateArticle({primaryKeyword:base.primaryKeyword||"",secondaryKeywords:base.secondaryKeywords||[],relatedEntities:base.relatedEntities||[],validInternalUrls},{title:row.title,description,content:row.content,claims:[]}),data={...base,description,seoScore:deterministicSeoScore(checks),auditReport:auditArticleIntelligence({title:row.title,description,content:row.content,frontmatter:base,brief:row.brief?.brief?.researchIntelligence||row.brief?.researchIntelligence||base.researchIntelligence,internalLinks:Array.isArray(base.internalLinkSuggestions)?base.internalLinkSuggestions:[]}),internalLinkStates:classifyInternalLinks(row.content,Array.isArray(base.internalLinkSuggestions)?base.internalLinkSuggestions:[],validInternalUrls)},warnings=eligibilityReasons({...row,description,frontmatter:data},checks,assets),blockers=publicationTechnicalBlockers({...row,description,frontmatter:data},assets,checks),readiness=blockers.length?"blocked":warnings.length?"ready-with-warnings":"ready",issues=[...blockers.map((reason:string,index:number)=>({id:`blocker-${index+1}`,severity:"blocker",message:reason,action:/image asset/i.test(reason)?"retry-images":"fix-and-recheck",actionLabel:/image asset/i.test(reason)?"Retry image":"Fix article"})),...warnings.map((reason:string,index:number)=>({id:`warning-${index+1}`,severity:"warning",message:reason,action:/image asset/i.test(reason)?"retry-images":"fix-and-recheck",actionLabel:/image asset/i.test(reason)?"Retry image":"Fix article"}))];return{slug:row.slug,version:row.updated_at,data:{...data,title:row.title,status:row.status,readiness,publishEligible:blockers.length===0,publishWarnings:warnings,publishEligibilityReasons:blockers,publishEligibilityIssues:issues,technicalBlockers:blockers},content:row.content,checks};}
async function publishedUrls(){return(await listCmsArticles("published")).map(row=>`/blog/${row.slug}`);}
export async function getCmsDraft(slug:string){const row=await getCmsArticle(slug,"draft");return row?evaluate(row,await listCmsAssets(row.id),await publishedUrls()):null;}
export async function repairCmsDraft(admin:BlogAdmin,slug:string){const row=await getCmsArticle(slug,"draft");if(!row)throw new Error(`Draft not found: ${slug}`);const base=row.frontmatter||{},brief=row.brief||{slug:row.slug,title:row.title,topic:base.topicSeed||row.title,primaryKeyword:base.primaryKeyword||row.title,secondaryKeywords:base.secondaryKeywords||[],relatedEntities:base.relatedEntities||[],searchIntent:base.searchIntent||"Informational",targetAudience:base.relevantExams||[base.audience||"Competitive-exam learners"],articleType:base.articleType||"Insight",internalLinks:base.internalLinkSuggestions||[]},result=await repairArticleOnce(brief,{title:row.title,description:row.description,content:row.content,qualityWarnings:base.qualityWarnings||[]}),data={...base,title:result.article.title,description:result.article.description,seoScore:result.editorial.dimensions.seo,contentQualityScore:result.editorial.overallScore,qualityDimensions:result.editorial.dimensions,seoIssues:result.deterministic.seoIssues,editorialIssues:result.deterministic.editorialIssues,qualityWarnings:[...result.deterministic.seoIssues,...result.deterministic.editorialIssues,...result.editorial.weaknesses,...result.editorial.unsupportedClaims],lastRepairAt:new Date().toISOString(),repairCycles:Number(base.repairCycles||0)+1};return saveCmsDraft(admin,slug,{data,content:result.article.content,expectedUpdatedAt:row.updated_at});}
export async function saveCmsDraft(admin:BlogAdmin,slug:string,input:{data?:Record<string,unknown>;content?:string;expectedUpdatedAt?:string}){const row=await getCmsArticle(slug,"draft");if(!row)throw new Error(`Draft not found: ${slug}`);const validInternalUrls=await publishedUrls(),data:Record<string,unknown>={...row.frontmatter,...input.data,status:"draft",updatedDate:new Date().toISOString().slice(0,10)},content=String(input.content??row.content),description=normalizeMetaDescription(data.description||row.description),checks=validateArticle({primaryKeyword:String(data.primaryKeyword||""),validInternalUrls},{title:String(data.title||row.title),description,content,claims:[]}),assets=await listCmsAssets(row.id),preview=evaluate({...row,title:String(data.title||row.title),description,content,frontmatter:{...data,description}},assets,validInternalUrls);data.description=description;data.seoIssues=checks.seoIssues;data.seoScore=deterministicSeoScore(checks);data.publishEligible=preview.data.publishEligible;data.publishEligibilityReasons=preview.data.publishEligibilityReasons;const updated=await updateCmsArticle(admin,slug,{title:String(data.title||row.title),description,content,frontmatter:data},input.expectedUpdatedAt||row.updated_at);return evaluate(updated,assets,validInternalUrls);}
export async function discardCmsDraft(admin:BlogAdmin,slug:string){const row=await getCmsArticle(slug,"draft");if(!row)throw new Error(`Draft not found: ${slug}`);await archiveCmsArticle(admin,slug,row.updated_at);return{discarded:true,archived:true,slug};}
function publishedResult(row:any){const data=row.frontmatter||{};return{publishedSlug:row.slug,title:row.title,seoScore:Number(data.seoScore),contentQualityScore:Number(data.contentQualityScore),category:data.category,status:"published",warnings:Array.isArray(data.publishWarnings)?data.publishWarnings:[],inProductionStore:true};}
export async function publishCmsDraft(admin:BlogAdmin,slug:string){const row=await getCmsArticle(slug);if(!row)throw new Error(`Draft not found: ${slug}`);if(row.status==="published")return publishedResult(row);if(row.status!=="draft")throw new Error(`Draft not found: ${slug}`);const assets=await listCmsAssets(row.id),draft=evaluate(row,assets,await publishedUrls()),data=draft.data,warnings=draft.data.publishWarnings as string[],blockers=draft.data.technicalBlockers as string[];if(blockers.length)throw new Error(`Publication failed: ${blockers.join(" ")}`);const now=new Date(),content=sanitizeCmsPublicCopy(row.content),title=sanitizeCmsPublicCopy(row.title),description=normalizeMetaDescription(sanitizeCmsPublicCopy(row.description));if(!title||!description||!content)throw new Error("Publication failed: required public article content was removed because it contained internal production notes. Review the draft and try again.");const publicData={...data,title,description,status:"published",readiness:warnings.length?"ready-with-warnings":"ready",publishEligible:true,publishWarnings:warnings,publishEligibilityReasons:[],technicalBlockers:[],updatedDate:now.toISOString().slice(0,10)};let updated;try{updated=await updateCmsArticle(admin,slug,{title,description,content,status:"published",published_at:now.toISOString(),frontmatter:publicData},row.updated_at);}catch(error){const current=await getCmsArticle(slug);if(current?.status==="published")return publishedResult(current);throw new Error(publicationPersistenceError(error));}return publishedResult(updated);}
