import "server-only";
/* eslint-disable @typescript-eslint/no-explicit-any -- validation and Supabase JSON payloads are runtime-shaped. */
import type { BlogAdmin } from "./blog-admin-auth";
import { archiveCmsArticle,getCmsArticle,listCmsAssets,updateCmsArticle } from "./blog-cms-db";
import { MIN_SCORE,validateArticle } from "./blog-engine";

const requiredFields=["title","description","date","image","imageAlt","category","author","primaryKeyword","secondaryKeywords","searchIntent","cluster","relevantExams","schemaType","seoScore","contentQualityScore"];
function normalizeMetaDescription(value:unknown){let text=String(value||"").replace(/\s+/g," ").trim();const supplement=" Learn practical methods, worked examples, and exam-focused guidance.";while(text.length<140)text+=supplement;if(text.length<=160)return text;let clipped=text.slice(0,159),boundary=clipped.lastIndexOf(" ");if(boundary>=140)clipped=clipped.slice(0,boundary);return `${clipped.replace(/[\s,;:.!?-]+$/g,"")}.`;}
function deterministicSeoScore(checks:any){return Math.max(0,100-checks.seoIssues.length*15-(checks.externalLinks.length?40:0)-(checks.invalidInternalLinks.length?20:0));}
function referencedAssets(row:any,assets:any[]){
  const data=row.frontmatter||{},content=String(row.content||""),inlineImages=Array.isArray(data.inlineImages)?data.inlineImages:[];
  return assets.filter((asset:any)=>{
    if(asset.status==="removed")return false;
    if(asset.asset_type==="featured"||asset.image_key==="featured")return Boolean(data.image);
    const image=inlineImages.find((item:any)=>item.id===asset.image_key);
    if(!image||image.status==="removed")return false;
    return Boolean((image.src&&content.includes(image.src))||content.includes(`inline-image:${image.id}`));
  });
}
function eligibilityReasons(row:any,checks:any,assets:any[]){const data=row.frontmatter||{},reasons:string[]=[];const missing=requiredFields.filter(key=>data[key]===undefined||data[key]===null||data[key]==="");if(missing.length)reasons.push(`Missing required frontmatter: ${missing.join(", ")}`);if(Number(data.seoScore)<80)reasons.push(`SEO score ${data.seoScore??"—"} is below 80.`);if(Number(data.contentQualityScore)<MIN_SCORE)reasons.push(`Content quality score ${data.contentQualityScore??"—"} is below ${MIN_SCORE}.`);if(checks.seoIssues.length)reasons.push(`Unresolved SEO issues: ${checks.seoIssues.join(" | ")}`);if(checks.editorialIssues?.length)reasons.push(`Unresolved editorial issues: ${checks.editorialIssues.join(" | ")}`);if(checks.externalLinks.length)reasons.push(`External article-body links found: ${checks.externalLinks.join(", ")}`);if(checks.invalidInternalLinks.length)reasons.push(`Invalid internal links found: ${checks.invalidInternalLinks.join(", ")}`);const unresolved=referencedAssets(row,assets).filter((asset:any)=>asset.status!=="generated"||!asset.public_url||!asset.storage_path||!asset.alt_text||(asset.asset_type==="featured"?data.image!==asset.public_url:!String(row.content||"").includes(asset.public_url)));if(unresolved.length)reasons.push(`Unresolved image assets: ${unresolved.map((asset:any)=>`${asset.image_key} (${asset.id}; ${asset.status})`).join(", ")}`);return reasons;}
function evaluate(row:any,assets:any[]=[]){const base=row.frontmatter||{},description=normalizeMetaDescription(row.description),checks=validateArticle({primaryKeyword:base.primaryKeyword||""},{title:row.title,description,content:row.content,claims:[]}),data={...base,description,seoScore:deterministicSeoScore(checks)},reasons=eligibilityReasons({...row,description,frontmatter:data},checks,assets);return{slug:row.slug,version:row.updated_at,data:{...data,title:row.title,status:row.status,publishEligible:reasons.length===0,publishEligibilityReasons:reasons},content:row.content,checks};}
export async function getCmsDraft(slug:string){const row=await getCmsArticle(slug,"draft");return row?evaluate(row,await listCmsAssets(row.id)):null;}
export async function saveCmsDraft(admin:BlogAdmin,slug:string,input:{data?:Record<string,unknown>;content?:string;expectedUpdatedAt?:string}){const row=await getCmsArticle(slug,"draft");if(!row)throw new Error(`Draft not found: ${slug}`);const data:Record<string,unknown>={...row.frontmatter,...input.data,status:"draft",updatedDate:new Date().toISOString().slice(0,10)},content=String(input.content??row.content),description=normalizeMetaDescription(data.description||row.description),checks=validateArticle({primaryKeyword:String(data.primaryKeyword||"")},{title:String(data.title||row.title),description,content,claims:[]}),assets=await listCmsAssets(row.id),preview=evaluate({...row,title:String(data.title||row.title),description,content,frontmatter:{...data,description}},assets);data.description=description;data.seoIssues=checks.seoIssues;data.seoScore=deterministicSeoScore(checks);data.publishEligible=preview.data.publishEligible;data.publishEligibilityReasons=preview.data.publishEligibilityReasons;const updated=await updateCmsArticle(admin,slug,{title:String(data.title||row.title),description,content,frontmatter:data},input.expectedUpdatedAt||row.updated_at);return evaluate(updated,assets);}
export async function discardCmsDraft(admin:BlogAdmin,slug:string){const row=await getCmsArticle(slug,"draft");if(!row)throw new Error(`Draft not found: ${slug}`);await archiveCmsArticle(admin,slug,row.updated_at);return{discarded:true,archived:true,slug};}
export async function publishCmsDraft(admin:BlogAdmin,slug:string){const row=await getCmsArticle(slug,"draft");if(!row)throw new Error(`Draft not found: ${slug}`);const assets=await listCmsAssets(row.id),draft=evaluate(row,assets),data=draft.data,reasons=draft.data.publishEligibilityReasons as string[];if(reasons.length)throw new Error(reasons.join(" "));const updated=await updateCmsArticle(admin,slug,{status:"published",description:String(data.description),frontmatter:{...data,status:"published",publishEligible:true,publishEligibilityReasons:[],updatedDate:new Date().toISOString().slice(0,10)}},row.updated_at);return{publishedSlug:slug,title:updated.title,seoScore:Number(data.seoScore),contentQualityScore:Number(data.contentQualityScore),category:data.category,status:"published",inProductionStore:true};}
