import "server-only";
/* eslint-disable @typescript-eslint/no-explicit-any -- generated MDX frontmatter is runtime-shaped JSON. */
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import type { BlogAdmin } from "./blog-admin-auth";
import { generateBlog } from "./blog-engine";
import { createCmsJob,getCmsJob,updateCmsJob,uploadBlogAsset,upsertCmsArticle } from "./blog-cms-db";

export const stages=["researching","brief","writing","reviewing","improving","featuredImage","imagePlanning","inlineImages","finalizing"] as const;
type Stage=(typeof stages)[number];type State="pending"|"processing"|"complete"|"failed";
export async function createBlogJob(admin:BlogAdmin,topic:string,audience:string,differentAngle=false){const job=await createCmsJob(admin,differentAngle?`${topic} — use a substantially different angle, structure, hook and original examples`:topic,audience);return{...job,differentAngle};}
export async function runBlogJob(admin:BlogAdmin,job:{id:string;topic:string;audience:string}){try{const result=await generateBlog({topic:job.topic,audience:job.audience,withImage:true,onProgress:async(stage:Stage,state:State,detail:Record<string,number>={})=>{const current=await getCmsJob(job.id),nextStages={...(current?.stages||{}),[stage]:state};await updateCmsJob(job.id,{stages:nextStages,progress:{stage,...detail}});}}) as {slug:string;filePath:string;briefPath?:string};const parsed=matter(fs.readFileSync(result.filePath,"utf8")),brief=result.briefPath&&fs.existsSync(result.briefPath)?JSON.parse(fs.readFileSync(result.briefPath,"utf8")):undefined;let row=await upsertCmsArticle(admin,{slug:result.slug,status:"draft",title:String(parsed.data.title),description:String(parsed.data.description||""),content:parsed.content,frontmatter:parsed.data,brief});const runtimeRoot=path.resolve(path.dirname(result.filePath),"../.."),assets=[{key:"featured",type:"featured" as const,src:String(parsed.data.image||""),prompt:String(parsed.data.imagePrompt||""),alt:String(parsed.data.imageAlt||"")},...(Array.isArray(parsed.data.inlineImages)?parsed.data.inlineImages:[]).filter((item:any)=>item.status==="generated"&&item.src).map((item:any)=>({key:String(item.id),type:"inline" as const,src:String(item.src),prompt:String(item.prompt||""),alt:String(item.alt||""),placement:String(item.placement||"")}))];let content=parsed.content;const frontmatter={...parsed.data};for(const asset of assets){if(!asset.src.startsWith("/blog/"))continue;const local=path.join(runtimeRoot,"public",asset.src.slice(1));if(!fs.existsSync(local))continue;const url=await uploadBlogAsset(row.id,asset.key,fs.readFileSync(local),{assetType:asset.type,prompt:asset.prompt,altText:asset.alt,placement:"placement" in asset?asset.placement:undefined});content=content.split(asset.src).join(url);if(asset.type==="featured")frontmatter.image=url;else if(Array.isArray(frontmatter.inlineImages))frontmatter.inlineImages=frontmatter.inlineImages.map((item:any)=>item.id===asset.key?{...item,src:url}:item);}row=await upsertCmsArticle(admin,{slug:result.slug,status:"draft",title:String(frontmatter.title),description:String(frontmatter.description||""),content,frontmatter,brief});await updateCmsJob(job.id,{status:"complete",result:{...result,filePath:null,persistentArticleId:row.id},completed_at:new Date().toISOString()});}catch(error){await updateCmsJob(job.id,{status:"failed",error:error instanceof Error?error.message:String(error),completed_at:new Date().toISOString()});}}
export async function getBlogJob(id:string){return getCmsJob(id);}
