import "server-only";
import { createClient } from "@supabase/supabase-js";
import type { BlogAdmin } from "./blog-admin-auth";
import { createBlogPost, type BlogFrontmatter, type BlogPost } from "./blog";

function settings(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase Blog CMS persistence is not configured.");return{url,key};}
function service(){const{url,key}=settings();return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});}
export function isCmsConfigured(){return Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY);}

export type CmsArticleRow={id:string;slug:string;status:"draft"|"published"|"archived";title:string;description:string;content:string;frontmatter:Record<string,unknown>;brief?:Record<string,unknown>;created_at:string;updated_at:string;published_at?:string};
export async function listCmsArticles(status?:CmsArticleRow["status"]){let query=service().from("blog_articles").select("*").order("updated_at",{ascending:false});if(status)query=query.eq("status",status);const{data,error}=await query;if(error)throw error;return(data||[]) as CmsArticleRow[];}
export async function getCmsArticle(slug:string,status?:CmsArticleRow["status"]){let query=service().from("blog_articles").select("*").eq("slug",slug);if(status)query=query.eq("status",status);const{data,error}=await query.maybeSingle();if(error)throw error;return data as CmsArticleRow|null;}
export async function upsertCmsArticle(admin:BlogAdmin,input:{slug:string;status?:CmsArticleRow["status"];title:string;description:string;content:string;frontmatter:Record<string,unknown>;brief?:Record<string,unknown>}){const payload={...input,status:input.status||"draft",created_by:admin.id,updated_by:admin.id}, {data,error}=await service().from("blog_articles").upsert(payload,{onConflict:"slug"}).select().single();if(error)throw error;return data as CmsArticleRow;}
export async function updateCmsArticle(admin:BlogAdmin,slug:string,input:Partial<Pick<CmsArticleRow,"title"|"description"|"content"|"frontmatter"|"brief"|"status"|"published_at">>,expectedUpdatedAt?:string){let query=service().from("blog_articles").update({...input,updated_by:admin.id}).eq("slug",slug);if(expectedUpdatedAt)query=query.eq("updated_at",expectedUpdatedAt);const{data,error}=await query.select().maybeSingle();if(error)throw error;if(!data)throw new Error("This article changed in another session. Reload it before saving again.");return data as CmsArticleRow;}
export async function archiveCmsArticle(admin:BlogAdmin,slug:string,expectedUpdatedAt?:string){return updateCmsArticle(admin,slug,{status:"archived"},expectedUpdatedAt);}
export function cmsRowToPost(row:CmsArticleRow):BlogPost{return createBlogPost(row.slug,{...(row.frontmatter||{}),title:row.title,description:row.description,status:row.status,date:String(row.frontmatter?.date||row.created_at.slice(0,10)),updatedDate:row.updated_at.slice(0,10)} as BlogFrontmatter,row.content);}
export async function getPublishedCmsPost(slug:string){const row=await getCmsArticle(slug,"published");return row?cmsRowToPost(row):null;}
export async function getPublishedCmsPosts(){return(await listCmsArticles("published")).map(cmsRowToPost);}

export async function createCmsJob(admin:BlogAdmin,topic:string,audience:string){const stages=Object.fromEntries(["researching","brief","writing","reviewing","improving","featuredImage","imagePlanning","inlineImages","finalizing"].map(stage=>[stage,"pending"]));const{data,error}=await service().from("blog_generation_jobs").insert({requested_by:admin.id,topic,audience,status:"processing",stages,started_at:new Date().toISOString(),attempt_count:1}).select().single();if(error)throw error;return data;}
export async function updateCmsJob(id:string,changes:Record<string,unknown>){const{data,error}=await service().from("blog_generation_jobs").update(changes).eq("id",id).select().single();if(error)throw error;return data;}
export async function getCmsJob(id:string){const{data,error}=await service().from("blog_generation_jobs").select("*").eq("id",id).maybeSingle();if(error)throw error;return data;}

export async function uploadBlogAsset(articleId:string,imageKey:string,bytes:Buffer,metadata:{assetType:"featured"|"inline";prompt:string;altText:string;placement?:string}){const bucket=process.env.BLOG_ASSET_BUCKET||"blog-assets",storagePath=`${articleId}/${imageKey}.png`,client=service(),upload=await client.storage.from(bucket).upload(storagePath,bytes,{contentType:"image/png",upsert:true});if(upload.error)throw upload.error;const publicUrl=client.storage.from(bucket).getPublicUrl(storagePath).data.publicUrl;const{error}=await client.from("blog_assets").upsert({article_id:articleId,asset_type:metadata.assetType,image_key:imageKey,prompt:metadata.prompt,alt_text:metadata.altText,placement:metadata.placement||null,status:"generated",public_url:publicUrl,storage_path:storagePath,generation_error:null},{onConflict:"article_id,image_key"});if(error)throw error;return publicUrl;}
export async function updateBlogAssetMetadata(articleId:string,imageKey:string,metadata:{assetType:"featured"|"inline";prompt:string;altText:string;placement?:string;status:string;publicUrl?:string|null;generationError?:string|null}){const{data,error}=await service().from("blog_assets").upsert({article_id:articleId,asset_type:metadata.assetType,image_key:imageKey,prompt:metadata.prompt,alt_text:metadata.altText,placement:metadata.placement||null,status:metadata.status,public_url:metadata.publicUrl??null,generation_error:metadata.generationError??null},{onConflict:"article_id,image_key"}).select().single();if(error)throw error;return data;}
export async function listCmsAssets(articleId:string){const{data,error}=await service().from("blog_assets").select("*").eq("article_id",articleId);if(error)throw error;return data||[];}
