import {NextResponse} from "next/server";
import {getBlogAdmin} from "@/lib/blog-admin-auth";
import {createGscProvider} from "@/lib/seo/providers/gsc.mjs";
import {createSupabaseSeoStore} from "@/lib/seo/store.mjs";
import {diagnoseSearchPerformance} from "@/lib/seo/intelligence.mjs";
import {getSeoCorpus} from "@/lib/seo/corpus";
import {seoRequestFingerprint} from "@/lib/seo/provider.mjs";

export const runtime="nodejs";
export const maxDuration=300;
export async function GET(){const admin=await getBlogAdmin();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const store=createSupabaseSeoStore();if(!store)return NextResponse.json({status:"UNAVAILABLE",reason:"SEO evidence store unavailable",recommendations:[]});try{const [rows,corpus]=await Promise.all([store.getSearchPerformance({days:90}),getSeoCorpus()]);return NextResponse.json({status:rows.length?"AVAILABLE":"UNAVAILABLE",source:"Google Search Console",observations:rows.length,recommendations:diagnoseSearchPerformance(rows,corpus),reason:rows.length?null:"No GSC observations have been ingested."});}catch{return NextResponse.json({status:"UNAVAILABLE",reason:"GSC evidence could not be loaded.",recommendations:[]});}}
export async function POST(){const admin=await getBlogAdmin();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const provider=createGscProvider(),store=createSupabaseSeoStore();if(!provider.configured||!store)return NextResponse.json({error:"GSC service account, property, or SEO store is unavailable."},{status:503});const end=new Date(Date.now()-3*86400000),start=new Date(end.getTime()-6*86400000),startDate=start.toISOString().slice(0,10),endDate=end.toISOString().slice(0,10),fingerprint=seoRequestFingerprint(provider.id,"search_performance",{keyword:`${process.env.GSC_PROPERTY}:${startDate}:${endDate}`});try{if(await store.findRecentSearchRun(fingerprint))return NextResponse.json({status:"CACHED",message:"This GSC period was synced within the last 24 hours."});const run=await store.beginRun({provider:provider.id,capability:"search_performance",fingerprint,requestMetadata:{startDate,endDate},adminId:admin.id});if(run?.deduplicated)return NextResponse.json({status:"PROCESSING",message:"An identical GSC sync is already active."},{status:202});if(!run?.id)throw new Error("GSC run could not be reserved.");const result=await provider.fetch("search_performance",{startDate,endDate});if(result.status==="SUCCESS")await store.persistSearchPerformance(result);await store.finishRun(run.id,result);return NextResponse.json({status:result.status,observations:result.data?.rows?.length||0,error:result.error?.message||null},{status:result.status==="SUCCESS"?200:503});}catch{return NextResponse.json({error:"GSC sync failed; no performance values were fabricated."},{status:503});}}
