import type {Metadata} from "next";
import LegalPage,{type LegalSection} from "../components/LegalPage";

export const metadata:Metadata={title:"Auctor Data Deletion Request",description:"Information on how Auctor users can request deletion of their personal data.",alternates:{canonical:"https://auctorlabs.in/data-deletion"},openGraph:{type:"website",url:"https://auctorlabs.in/data-deletion",siteName:"Auctor Labs",title:"Auctor Data Deletion Request",description:"Information on how Auctor users can request deletion of their personal data."}};
const email="mailto:info@auctorlabs.in?subject=Auctor%20Data%20Deletion%20Request";
const sections:LegalSection[]=[
 {id:"data-covered",title:"What Data May Be Deleted",content:<p>A deletion request may cover account and profile information, contact information, educational information you provided, practice and assessment history, service activity associated with your account, support correspondence, and WhatsApp-related information held by Auctor. The exact data involved depends on the services you used and the information available to identify your account.</p>},
 {id:"request",title:"How to Request Deletion",content:<><p>Email <a href={email}>info@auctorlabs.in</a> with the subject “Auctor Data Deletion Request.” Use an email address associated with your Auctor account where possible. In the message, identify the account or phone number concerned and state that you want your personal data deleted.</p><p>Do not send your password, one-time password, payment credentials, or unnecessary identity documents.</p></>},
 {id:"verification",title:"Identity and Account Verification",content:<p>To protect users from unauthorized deletion, we may ask you to verify control of the relevant email address, phone number, WhatsApp number, or account. We will request only information reasonably necessary to confirm the request.</p>},
 {id:"after-request",title:"What Happens After a Request",content:<p>We will review the request, verify it where necessary, identify relevant Auctor systems, and communicate the outcome or any information needed to proceed. This is currently a manual request process; submitting an email does not represent an instant or automated deletion.</p>},
 {id:"retention",title:"Information We May Need to Retain",content:<p>Some information may be retained when reasonably necessary for security, fraud prevention, dispute resolution, financial or transaction records, enforcing agreements, exercising legal rights, or complying with applicable obligations. Where appropriate, information may instead be restricted or anonymized. Data controlled independently by third-party services remains subject to those services’ own deletion processes.</p>},
 {id:"contact",title:"Questions About Your Request",content:<p>For questions or updates about a deletion request, contact <a href="mailto:info@auctorlabs.in">info@auctorlabs.in</a> and reference your original request. Please avoid including sensitive credentials.</p>},
];
export default function DataDeletion(){return <LegalPage title="Auctor Data Deletion Request" introduction="You can ask Auctor to delete personal information associated with your account or interactions. This page explains the current manual request process and what to expect." sections={sections}><a href={email} className="mt-8 inline-flex rounded-lg bg-orange-500 px-5 py-3 font-semibold text-black transition hover:bg-orange-400">Request Data Deletion</a></LegalPage>;}
