import assert from "node:assert/strict";
import test,{afterEach} from "node:test";
import "./helpers/blog-studio-harness.mjs";
import {JSDOM} from "jsdom";
const dom=new JSDOM('<div id="root"></div>');globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.HTMLElement=dom.window.HTMLElement;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const {createElement,act}=await import("react"),{createRoot}=await import("react-dom/client"),{default:ImageTools}=await import("../app/admin/blog/image-tools.tsx");
let root,calls;
const button=label=>[...document.querySelectorAll('button')].find(b=>b.textContent===label);
const click=async label=>act(async()=>button(label).click());
const edit=async(element,value)=>act(async()=>{const prototype=element.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,'value').set.call(element,value);element.dispatchEvent(new dom.window.Event('input',{bubbles:true}));});
async function setup(){calls=[];root=createRoot(document.getElementById('root'));await act(async()=>root.render(createElement(ImageTools,{data:{inlineImages:[{id:'one',role:'human',status:'proposed',src:'https://cdn.test/one.png',alt:'Student scanning a passage',conceptDescription:'Time pressure',placement:'insight'}]},busy:false,dirty:false,placement:'insight',headings:[{value:'insight',label:'Insight'}],onPlacement:()=>{},onImage:async(...args)=>{calls.push(args)}})));}
afterEach(async()=>{await act(async()=>root?.unmount());});
test('Replace opens an empty prompt without generating; Cancel leaves candidate intact',async()=>{await setup();await click('Replace');assert.ok(document.querySelector('[aria-label="Replace image"]'));assert.equal(calls.length,0);assert.equal(button('Generate replacement').disabled,true);await click('Cancel');assert.equal(document.querySelector('[aria-label="Replace image"]'),null);assert.ok(document.querySelector('[data-image-id="one"]'));});
test('replacement submits actual user prompt and explicit role',async()=>{await setup();await click('Replace');await edit(document.querySelector('textarea'),'A comparison diagram with arrows');await act(async()=>{const select=document.querySelector('select');select.value='supporting_visual';select.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});await click('Generate replacement');assert.deepEqual(calls,[['regenerate-inline','one',{direction:'A comparison diagram with arrows',role:'supporting_visual'}]]);});
test('Add Image offers generation and upload, with optional guidance',async()=>{await setup();await click('+ Add Image');assert.ok(button('Upload Image'));await click('Generate with Birbal');assert.ok(document.querySelector('textarea[placeholder="Tell Birbal what you want the images to show..."]'));await click('Generate image');assert.equal(calls[0][2].direction,'');await edit(document.querySelector('textarea'),'Show a learner stepping back from the passage');await click('Generate image');assert.match(calls[1][2].direction,/stepping back/);});
test('upload submits file, concept, alt and role into the image callback',async()=>{await setup();await click('+ Add Image');await click('Upload Image');const file=new dom.window.File(['bytes'],'mine.png',{type:'image/png'});await act(async()=>{const input=document.querySelector('input[type="file"]');Object.defineProperty(input,'files',{value:[file]});input.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});await edit(document.querySelector('textarea'),'A learner teaching a group');await edit(document.querySelector('input:not([type="file"])'),'Group discussion');await click('Upload for review');assert.equal(calls[0][0],'upload-inline');assert.equal(calls[0][2].file,file);assert.equal(calls[0][2].role,'human');assert.equal(calls[0][2].alt,'Group discussion');});
test('thumbnail opens larger preview and closes in place',async()=>{await setup();await act(async()=>document.querySelector('button[aria-label^="Preview"]').click());const dialog=document.querySelector('dialog');assert.ok(dialog.hasAttribute('open'));assert.equal(dialog.querySelector('img').src,'https://cdn.test/one.png');await click('Close preview');assert.equal(document.querySelector('dialog'),null);assert.equal(calls.length,0);});
