import assert from "node:assert/strict";
import test from "node:test";
import { extractArticleHeadings, tocHeadings, validateArticleHeadings } from "../lib/blog-headings.mjs";
import { classifyInternalLinks } from "../lib/blog-links.mjs";
import { lifecycleTarget } from "../lib/blog-lifecycle.mjs";
import { canRetryGenerationJob, classifyGenerationFailure } from "../lib/blog-job-policy.mjs";
import { publicationTechnicalBlockers } from "../lib/blog-publish-policy.ts";
import { mergePublishedBlogPosts } from "../lib/blog.ts";

const post=(slug,title,status="published")=>({slug,title,status,description:title,date:"2026-09-07",content:"## Valid section",readingTime:1,wordCount:2});
test("Supabase wins slug collisions and nonpublished CMS ownership suppresses legacy files",()=>{const database=[post("collision","Database")],files=[post("collision","File"),post("legacy","Legacy"),post("archived-collision","Old file")],owned=new Set(["collision","archived-collision"]),merged=mergePublishedBlogPosts(database,files,owned);assert.deepEqual(merged.map(item=>[item.slug,item.title]),[["collision","Database"],["legacy","Legacy"]]);});

test("TOC includes H2/H3, excludes H1, and gives duplicate headings unique IDs",()=>{const content="# Body H1\n\n## Method\n\n### Evidence\n\n## Method";assert.deepEqual(tocHeadings(content).map(({text,id,level})=>({text,id,level})),[{text:"Method",id:"method",level:2},{text:"Evidence",id:"evidence",level:3},{text:"Method",id:"method-2",level:2}]);assert.equal(new Set(extractArticleHeadings(content).map(item=>item.id)).size,4);});
test("placeholder, duplicate, empty, body H1 and hierarchy defects are deterministic",()=>{const result=validateArticleHeadings("# Wrong\n\n## Heading\n\n## Heading\n\n#### Jump\n\n##");assert.ok(result.issues.some(x=>x.includes("placeholder")));assert.ok(result.issues.some(x=>x.includes("duplicate")));assert.ok(result.issues.some(x=>x.includes("empty")));assert.ok(result.issues.some(x=>x.includes("must not contain an H1")));assert.ok(result.issues.some(x=>x.includes("hierarchy")));});
test("publication blocks malformed structure and broken links but not editorial scores",()=>{const row={slug:"valid-slug",title:"Title",description:"Description",content:"## Heading",frontmatter:{date:"2026-09-07",author:"Auctor"}};const blockers=publicationTechnicalBlockers(row,[],{invalidInternalLinks:["/blog/missing"]});assert.ok(blockers.some(x=>x.includes("placeholder")));assert.ok(blockers.some(x=>x.includes("Broken internal links")));});
test("internal link states reflect the article body rather than suggestions",()=>{const states=classifyInternalLinks("[Inserted](/blog/live) [Broken](/blog/gone)",[{url:"/blog/suggested",anchor:"Suggestion"}],["/blog/live"]);assert.equal(states.find(x=>x.url==="/blog/suggested").state,"SUGGESTED");assert.equal(states.find(x=>x.url==="/blog/live").state,"VERIFIED");assert.equal(states.find(x=>x.url==="/blog/gone").state,"BROKEN");});
test("lifecycle transitions keep unpublish, edit, archive, restore, and delete distinct",()=>{assert.equal(lifecycleTarget("published","unpublish"),"unpublished");assert.equal(lifecycleTarget("published","archive"),null);assert.equal(lifecycleTarget("unpublished","edit"),"draft");assert.equal(lifecycleTarget("unpublished","archive"),"archived");assert.equal(lifecycleTarget("archived","restore"),"draft");assert.equal(lifecycleTarget("draft","delete"),null);});
test("generation failure and retry policy distinguish permanent, transient, timeout and exhausted jobs",()=>{assert.equal(classifyGenerationFailure(new Error("network reset")),"transient");assert.equal(classifyGenerationFailure(new Error("OPENAI_API_KEY is required")),"permanent");assert.equal(canRetryGenerationJob({status:"failed",failure_kind:"timeout",attempt_count:1,max_attempts:3}),true);assert.equal(canRetryGenerationJob({status:"failed",failure_kind:"transient",attempt_count:3,max_attempts:3}),false);});
