import test from "node:test";
import assert from "node:assert/strict";
import {buildResearchIntelligence,auditArticleIntelligence,diagnoseSearchPerformance} from "../lib/seo/intelligence.mjs";
import {createGscProvider} from "../lib/seo/providers/gsc.mjs";
import {isValidResearchKeyword} from "../lib/seo/provider.mjs";
import {refreshProviderEvidence} from "../lib/seo/refresh.mjs";

test("paid keyword paths reject pathological input while normal editorial queries remain valid",()=>{for(const keyword of ["CAT VARC preparation","CAT 2027","reading comprehension questions","RC questions for CAT","CLAT reading comprehension"])assert.equal(isValidResearchKeyword(keyword),true);for(const keyword of ["","  ","a".repeat(121),"keyword;another","CAT\u0000VARC","x".repeat(30)])assert.equal(isValidResearchKeyword(keyword),false);});
test("fresh keyword cache bypasses admin quota; quota rejection precedes provider",async()=>{let providerCalls=0,reservations=0,hasCache=true;const provider={id:"dataforseo",capabilities:["keyword_metrics"],fetch:async()=>{providerCalls++;throw new Error("Paid provider must not run")}},store={findFreshMetric:async()=>hasCache?{id:"existing",fetched_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString(),data:{searchVolume:100}}:null,beginRun:async()=>{reservations++;return{quotaExceeded:true}}};const request={keyword:"CAT VARC preparation",country:"IN",language:"en",device:"desktop",searchEngine:"google"},cached=await refreshProviderEvidence({provider,capability:"keyword_metrics",request,store,adminId:"owner-id",paidDailyLimit:20});assert.equal(cached.status,"CACHED");assert.equal(reservations,0);hasCache=false;const blocked=await refreshProviderEvidence({provider,capability:"keyword_metrics",request:{...request,keyword:"CLAT reading comprehension"},store,adminId:"owner-id",paidDailyLimit:20});assert.equal(blocked.error.code,"QUOTA_EXCEEDED");assert.equal(reservations,1);assert.equal(providerCalls,0);});

test("research decisions use provider metrics and assigned CMS keywords without inventing missing SERP or trend data",()=>{const corpus=[{slug:"cat-varc-guide",url:"/blog/cat-varc-guide",title:"CAT VARC Guide",primaryKeyword:"CAT VARC preparation",secondaryKeywords:[],searchIntent:"Informational",cluster:"CAT",status:"published",headings:["Reading strategy"],text:"cat varc preparation reading strategy"}],metrics={status:"CACHED",data:{searchVolume:1200,cpc:0.42,keywordDifficulty:35}},result=buildResearchIntelligence({keyword:"cat varc preparation",metrics,trend:{status:"CACHED",data:{timeline:[]}},corpus});assert.equal(result.opportunity.action,"UPDATE");assert.equal(result.opportunity.article,"cat-varc-guide");assert.ok(result.opportunity.components.some(item=>item.name==="Demand"&&item.evidence.searchVolume===1200));assert.equal(result.briefContext.evidenceStatus.serp,"UNAVAILABLE");assert.ok(result.opportunity.unavailableMetrics.includes("SERP weakness"));assert.ok(result.opportunity.unavailableMetrics.includes("Trend"));});
test("prepublish audit prioritizes observed gaps and does not change draft data",()=>{const frontmatter={primaryKeyword:"CAT VARC preparation"},report=auditArticleIntelligence({title:"CAT VARC preparation",description:"Short",content:"## Strategy\nA short note.",frontmatter,brief:{userQuestions:["How to prepare for CAT VARC?"],entitiesToCover:[]}});assert.ok(report.overallScore<100);assert.ok(report.fixes.some(item=>item.severity==="HIGH"));assert.equal(frontmatter.primaryKeyword,"CAT VARC preparation");});
test("GSC diagnoses observed low CTR and position opportunity",()=>{const corpus=[{slug:"cat-varc-guide",title:"CAT VARC Guide"}],rows=[{page:"https://auctorlabs.in/blog/cat-varc-guide",query:"CAT VARC strategy",observation_date:"2026-09-10",clicks:2,impressions:200,ctr:.01,average_position:11.4}];const output=diagnoseSearchPerformance(rows,corpus);assert.ok(output.some(item=>item.type==="LOW_CTR"&&item.metrics.impressions===200));assert.ok(output.some(item=>item.type==="POSITION_5_20"&&item.metrics.averagePosition===11.4));});
test("GSC provider uses OAuth refresh-token authentication and Search Analytics with a mocked client",async()=>{const calls=[];const httpClient=async(url,options)=>{calls.push({url,options});if(url.includes("oauth2"))return{ok:true,json:async()=>({access_token:"mock-token"})};return{ok:true,json:async()=>({rows:[{keys:["2026-09-10","CAT VARC","https://auctorlabs.in/blog/cat-varc-guide","ind","DESKTOP"],clicks:3,impressions:100,ctr:.03,position:9.5}]})};};const provider=createGscProvider({clientId:"mock-client-id",clientSecret:"mock-client-secret",refreshToken:"mock-refresh-token",property:"sc-domain:auctorlabs.in",httpClient}),result=await provider.fetch("search_performance",{startDate:"2026-09-10",endDate:"2026-09-10"});assert.equal(result.status,"SUCCESS");assert.equal(result.data.rows[0].average_position,9.5);assert.equal(result.costMetadata.amount,0);assert.equal(calls.length,2);assert.equal(calls[0].url,"https://oauth2.googleapis.com/token");assert.deepEqual(Object.fromEntries(calls[0].options.body),{grant_type:"refresh_token",client_id:"mock-client-id",client_secret:"mock-client-secret",refresh_token:"mock-refresh-token"});assert.equal(calls[1].options.headers.Authorization,"Bearer mock-token");assert.ok(calls[1].url.includes("searchAnalytics/query"));});
test("GSC provider reports missing OAuth configuration without making a request",async()=>{let calls=0;const provider=createGscProvider({clientId:"",clientSecret:"",refreshToken:"",property:"sc-domain:auctorlabs.in",httpClient:async()=>{calls++;}}),result=await provider.fetch("search_performance",{startDate:"2026-09-10",endDate:"2026-09-10"});assert.equal(result.status,"UNAVAILABLE");assert.equal(result.error.code,"MISSING_CREDENTIAL");assert.match(result.error.message,/OAuth client ID, client secret, and refresh token/);assert.equal(calls,0);});
